module.exports = {
  LOGIN: "lOGIN",
  LOGOUT: "LOGOUT",
  LOADING_UI: "LOADING_UI",
  UNLOADING_UI: "UNLOADING_UI",
  SET_ERRORS: "SET_ERRORS",
  UNSET_ERRORS: "UNSET_ERRORS",
  //filers
  ADD_FILTER: "ADD_FILTER",
  SET_START_DATE: "SET_START_DATE",
  SET_END_DATE: "SET_END_DATE",
  SORT_BY_LIKES: "SORT_BY_LIKES",
  SORT_BY_DATE: "SORT_BY_DATE",
  SET_USER_TYPE: "SET_USER_TYPE",
  //employer
  ADD_EMPLOYER_PROFILE: "ADD_EMPLOYER_PROFILE",
  ADD_INTERNSHIP: "ADD_INTERNSHIP",

  //student
  ADD_STUDENT_PROFILE: "ADD_STUDENT_PROFILE",
  ADD_STUDENT_EXPERTISE: "ADD_STUDENT_EXPERTISE",

  //internship
  SHOW_INTERNSHIP: "SHOW_INTERNSHIP",
  ADD_CURRENT: "ADD_CURRENT",
  SET_INTERNSHIPS: "SET_INTERNSHIPS",

  //tests
  ADD_TESTS: "ADD_TESTS",
  ADD_QUESTIONS: "ADD_QUESTIONS",
  ADD_ANSWERS: "ADD_ANSWERS",
  ADD_RESPONSE: "ADD-RESPONSE",
  CURRENT_TEST: "CURRENT_TEST",
  CURRENT_ANSWERS: "CURRENT_ANSWERS",
  QUESTION_STATE: "QUESTION_STATE",
  TEST_STATE: "TEST_STATE",
  SET_USER: "SET_USER",
  GET_DIFFICULTY: "GET_DIFFICULTY",
  SET_CURRENT_ITEM: "SET_CURRENT_ITEM",
  SET_TEST_COMPLETED: "SET_TEST_COMPLETED",
  CLEAR_RESPONSE: "CLEAR_RESPONSE",
};
