const sortCityBasedOnKey = (a, b) => {
  const keyA = a.key.toUpperCase();
  const keyB = b.key.toUpperCase();

  let comparison = 0;
  if (keyA > keyB) {
    comparison = 1;
  } else if (keyA < keyB) {
    comparison = -1;
  }
  return comparison;
};

export const cities = [
  {
    key: "Andaman And Nicobar Islands",
    value: "Andaman And Nicobar Islands",
    text: "Andaman And Nicobar Islands",
  },
  { key: "Port Blair", value: "Port Blair", text: "Port Blair" },
  { key: "Andhra Pradesh", value: "Andhra Pradesh", text: "Andhra Pradesh" },
  { key: "Adoni", value: "Adoni", text: "Adoni" },
  { key: "Amaravati", value: "Amaravati", text: "Amaravati" },
  { key: "Anantapur", value: "Anantapur", text: "Anantapur" },
  { key: "Chandragiri", value: "Chandragiri", text: "Chandragiri" },
  { key: "Chittoor", value: "Chittoor", text: "Chittoor" },
  { key: "Dowlaiswaram", value: "Dowlaiswaram", text: "Dowlaiswaram" },
  { key: "Eluru", value: "Eluru", text: "Eluru" },
  { key: "Guntur", value: "Guntur", text: "Guntur" },
  { key: "Kadapa", value: "Kadapa", text: "Kadapa" },
  { key: "Kakinada", value: "Kakinada", text: "Kakinada" },
  { key: "Kurnool", value: "Kurnool", text: "Kurnool" },
  { key: "Machilipatnam", value: "Machilipatnam", text: "Machilipatnam" },
  { key: "Nagarjunakoṇḍa", value: "Nagarjunakoṇḍa", text: "Nagarjunakoṇḍa" },
  { key: "Rajahmundry", value: "Rajahmundry", text: "Rajahmundry" },
  { key: "Srikakulam", value: "Srikakulam", text: "Srikakulam" },
  { key: "Tirupati", value: "Tirupati", text: "Tirupati" },
  { key: "Vijayawada", value: "Vijayawada", text: "Vijayawada" },
  { key: "Visakhapatnam", value: "Visakhapatnam", text: "Visakhapatnam" },
  { key: "Vizianagaram", value: "Vizianagaram", text: "Vizianagaram" },
  { key: "Yemmiganur", value: "Yemmiganur", text: "Yemmiganur" },
  {
    key: "Arunachal Pradesh",
    value: "Arunachal Pradesh",
    text: "Arunachal Pradesh",
  },
  { key: "Itanagar", value: "Itanagar", text: "Itanagar" },
  { key: "Assam", value: "Assam", text: "Assam" },
  { key: "Dhuburi", value: "Dhuburi", text: "Dhuburi" },
  { key: "Dibrugarh", value: "Dibrugarh", text: "Dibrugarh" },
  { key: "Dispur", value: "Dispur", text: "Dispur" },
  { key: "Guwahati", value: "Guwahati", text: "Guwahati" },
  { key: "Jorhat", value: "Jorhat", text: "Jorhat" },
  { key: "Nagaon", value: "Nagaon", text: "Nagaon" },
  { key: "Sibsagar", value: "Sibsagar", text: "Sibsagar" },
  { key: "Silchar", value: "Silchar", text: "Silchar" },
  { key: "Tezpur", value: "Tezpur", text: "Tezpur" },
  { key: "Tinsukia", value: "Tinsukia", text: "Tinsukia" },
  { key: "Bihar", value: "Bihar", text: "Bihar" },
  { key: "Ara", value: "Ara", text: "Ara" },
  { key: "Baruni", value: "Baruni", text: "Baruni" },
  { key: "Begusarai", value: "Begusarai", text: "Begusarai" },
  { key: "Bettiah", value: "Bettiah", text: "Bettiah" },
  { key: "Bhagalpur", value: "Bhagalpur", text: "Bhagalpur" },
  { key: "Bihar Sharif", value: "Bihar Sharif", text: "Bihar Sharif" },
  { key: "Bodh Gaya", value: "Bodh Gaya", text: "Bodh Gaya" },
  { key: "Buxar", value: "Buxar", text: "Buxar" },
  { key: "Chapra", value: "Chapra", text: "Chapra" },
  { key: "Darbhanga", value: "Darbhanga", text: "Darbhanga" },
  { key: "Dehri", value: "Dehri", text: "Dehri" },
  { key: "Dinapur Nizamat", value: "Dinapur Nizamat", text: "Dinapur Nizamat" },
  { key: "Gaya", value: "Gaya", text: "Gaya" },
  { key: "Hajipur", value: "Hajipur", text: "Hajipur" },
  { key: "Jamalpur", value: "Jamalpur", text: "Jamalpur" },
  { key: "Katihar", value: "Katihar", text: "Katihar" },
  { key: "Madhubani", value: "Madhubani", text: "Madhubani" },
  { key: "Motihari", value: "Motihari", text: "Motihari" },
  { key: "Munger", value: "Munger", text: "Munger" },
  { key: "Muzaffarpur", value: "Muzaffarpur", text: "Muzaffarpur" },
  { key: "Patna", value: "Patna", text: "Patna" },
  { key: "Purnia", value: "Purnia", text: "Purnia" },
  { key: "Pusa", value: "Pusa", text: "Pusa" },
  { key: "Saharsa", value: "Saharsa", text: "Saharsa" },
  { key: "Samastipur", value: "Samastipur", text: "Samastipur" },
  { key: "Sasaram", value: "Sasaram", text: "Sasaram" },
  { key: "Sitamarhi", value: "Sitamarhi", text: "Sitamarhi" },
  { key: "Siwan", value: "Siwan", text: "Siwan" },
  { key: "Chhattisgarh", value: "Chhattisgarh", text: "Chhattisgarh" },
  { key: "Ambikapur", value: "Ambikapur", text: "Ambikapur" },
  { key: "Bhilai", value: "Bhilai", text: "Bhilai" },
  { key: "Bilaspur", value: "Bilaspur", text: "Bilaspur" },
  { key: "Dhamtari", value: "Dhamtari", text: "Dhamtari" },
  { key: "Durg", value: "Durg", text: "Durg" },
  { key: "Jagdalpur", value: "Jagdalpur", text: "Jagdalpur" },
  { key: "Raipur", value: "Raipur", text: "Raipur" },
  { key: "Rajnandgaon", value: "Rajnandgaon", text: "Rajnandgaon" },
  {
    key: "Dadra And Nagar Haveli",
    value: "Dadra And Nagar Haveli",
    text: "Dadra And Nagar Haveli",
  },
  { key: "Silvassa", value: "Silvassa", text: "Silvassa" },
  { key: "Daman And Diu", value: "Daman And Diu", text: "Daman And Diu" },
  { key: "Daman", value: "Daman", text: "Daman" },
  { key: "Diu", value: "Diu", text: "Diu" },
  { key: "Delhi", value: "Delhi", text: "Delhi" },
  { key: "New Delhi", value: "New Delhi", text: "New Delhi" },
  { key: "Goa", value: "Goa", text: "Goa" },
  { key: "Madgaon", value: "Madgaon", text: "Madgaon" },
  { key: "Panaji", value: "Panaji", text: "Panaji" },
  { key: "Gujarat", value: "Gujarat", text: "Gujarat" },
  { key: "Ahmadabad", value: "Ahmadabad", text: "Ahmadabad" },
  { key: "Amreli", value: "Amreli", text: "Amreli" },
  { key: "Bharuch", value: "Bharuch", text: "Bharuch" },
  { key: "Bhavnagar", value: "Bhavnagar", text: "Bhavnagar" },
  { key: "Bhuj", value: "Bhuj", text: "Bhuj" },
  { key: "Dwarka", value: "Dwarka", text: "Dwarka" },
  { key: "Gandhinagar", value: "Gandhinagar", text: "Gandhinagar" },
  { key: "Godhra", value: "Godhra", text: "Godhra" },
  { key: "Jamnagar", value: "Jamnagar", text: "Jamnagar" },
  { key: "Junagadh", value: "Junagadh", text: "Junagadh" },
  { key: "Kandla", value: "Kandla", text: "Kandla" },
  { key: "Khambhat", value: "Khambhat", text: "Khambhat" },
  { key: "Kheda", value: "Kheda", text: "Kheda" },
  { key: "Mahesana", value: "Mahesana", text: "Mahesana" },
  { key: "Morvi", value: "Morvi", text: "Morvi" },
  { key: "Nadiad", value: "Nadiad", text: "Nadiad" },
  { key: "Navsari", value: "Navsari", text: "Navsari" },
  { key: "Okha", value: "Okha", text: "Okha" },
  { key: "Palanpur", value: "Palanpur", text: "Palanpur" },
  { key: "Patan", value: "Patan", text: "Patan" },
  { key: "Porbandar", value: "Porbandar", text: "Porbandar" },
  { key: "Rajkot", value: "Rajkot", text: "Rajkot" },
  { key: "Surat", value: "Surat", text: "Surat" },
  { key: "Surendranagar", value: "Surendranagar", text: "Surendranagar" },
  { key: "Valsad", value: "Valsad", text: "Valsad" },
  { key: "Veraval", value: "Veraval", text: "Veraval" },
  { key: "Haryana", value: "Haryana", text: "Haryana" },
  { key: "Ambala", value: "Ambala", text: "Ambala" },
  { key: "Bhiwani", value: "Bhiwani", text: "Bhiwani" },
  { key: "Chandigarh", value: "Chandigarh", text: "Chandigarh" },
  { key: "Faridabad", value: "Faridabad", text: "Faridabad" },
  { key: "Firozpur Jhirka", value: "Firozpur Jhirka", text: "Firozpur Jhirka" },
  { key: "Gurgaon", value: "Gurgaon", text: "Gurgaon" },
  { key: "Hansi", value: "Hansi", text: "Hansi" },
  { key: "Hisar", value: "Hisar", text: "Hisar" },
  { key: "Jind", value: "Jind", text: "Jind" },
  { key: "Kaithal", value: "Kaithal", text: "Kaithal" },
  { key: "Karnal", value: "Karnal", text: "Karnal" },
  { key: "Kurukshetra", value: "Kurukshetra", text: "Kurukshetra" },
  { key: "Panipat", value: "Panipat", text: "Panipat" },
  { key: "Pehowa", value: "Pehowa", text: "Pehowa" },
  { key: "Rewari", value: "Rewari", text: "Rewari" },
  { key: "Rohtak", value: "Rohtak", text: "Rohtak" },
  { key: "Sirsa", value: "Sirsa", text: "Sirsa" },
  { key: "Sonipat", value: "Sonipat", text: "Sonipat" },
  {
    key: "Himachal Pradesh",
    value: "Himachal Pradesh",
    text: "Himachal Pradesh",
  },
  { key: "Chamba", value: "Chamba", text: "Chamba" },
  { key: "Dalhousie", value: "Dalhousie", text: "Dalhousie" },
  { key: "Dharmshala", value: "Dharmshala", text: "Dharmshala" },
  { key: "Hamirpur", value: "Hamirpur", text: "Hamirpur" },
  { key: "Kangra", value: "Kangra", text: "Kangra" },
  { key: "Kullu", value: "Kullu", text: "Kullu" },
  { key: "Mandi", value: "Mandi", text: "Mandi" },
  { key: "Nahan", value: "Nahan", text: "Nahan" },
  { key: "Shimla", value: "Shimla", text: "Shimla" },
  { key: "Una", value: "Una", text: "Una" },
  {
    key: "Jammu And Kashmir",
    value: "Jammu And Kashmir",
    text: "Jammu And Kashmir",
  },
  { key: "Anantnag", value: "Anantnag", text: "Anantnag" },
  { key: "Baramula", value: "Baramula", text: "Baramula" },
  { key: "Doda", value: "Doda", text: "Doda" },
  { key: "Gulmarg", value: "Gulmarg", text: "Gulmarg" },
  { key: "Jammu", value: "Jammu", text: "Jammu" },
  { key: "Kathua", value: "Kathua", text: "Kathua" },
  { key: "Leh", value: "Leh", text: "Leh" },
  { key: "Punch", value: "Punch", text: "Punch" },
  { key: "Rajauri", value: "Rajauri", text: "Rajauri" },
  { key: "Srinagar", value: "Srinagar", text: "Srinagar" },
  { key: "Udhampur", value: "Udhampur", text: "Udhampur" },
  { key: "Jharkhand", value: "Jharkhand", text: "Jharkhand" },
  { key: "Bokaro", value: "Bokaro", text: "Bokaro" },
  { key: "Chaibasa", value: "Chaibasa", text: "Chaibasa" },
  { key: "Deoghar", value: "Deoghar", text: "Deoghar" },
  { key: "Dhanbad", value: "Dhanbad", text: "Dhanbad" },
  { key: "Dumka", value: "Dumka", text: "Dumka" },
  { key: "Giridih", value: "Giridih", text: "Giridih" },
  { key: "Hazaribag", value: "Hazaribag", text: "Hazaribag" },
  { key: "Jamshedpur", value: "Jamshedpur", text: "Jamshedpur" },
  { key: "Jharia", value: "Jharia", text: "Jharia" },
  { key: "Rajmahal", value: "Rajmahal", text: "Rajmahal" },
  { key: "Ranchi", value: "Ranchi", text: "Ranchi" },
  { key: "Saraikela", value: "Saraikela", text: "Saraikela" },
  { key: "Karnataka", value: "Karnataka", text: "Karnataka" },
  { key: "Badami", value: "Badami", text: "Badami" },
  { key: "Ballari", value: "Ballari", text: "Ballari" },
  { key: "Bangalore", value: "Bangalore", text: "Bangalore" },
  { key: "Belgavi", value: "Belgavi", text: "Belgavi" },
  { key: "Bhadravati", value: "Bhadravati", text: "Bhadravati" },
  { key: "Bidar", value: "Bidar", text: "Bidar" },
  { key: "Chikkamagaluru", value: "Chikkamagaluru", text: "Chikkamagaluru" },
  { key: "Chitradurga", value: "Chitradurga", text: "Chitradurga" },
  { key: "Davangere", value: "Davangere", text: "Davangere" },
  { key: "Halebid", value: "Halebid", text: "Halebid" },
  { key: "Hassan", value: "Hassan", text: "Hassan" },
  {
    key: "Hubballi Dharwad",
    value: "Hubballi Dharwad",
    text: "Hubballi Dharwad",
  },
  { key: "Kalaburagi", value: "Kalaburagi", text: "Kalaburagi" },
  { key: "Kolar", value: "Kolar", text: "Kolar" },
  { key: "Madikeri", value: "Madikeri", text: "Madikeri" },
  { key: "Mandya", value: "Mandya", text: "Mandya" },
  { key: "Mangaluru", value: "Mangaluru", text: "Mangaluru" },
  { key: "Mysuru", value: "Mysuru", text: "Mysuru" },
  { key: "Raichur", value: "Raichur", text: "Raichur" },
  { key: "Shivamogga", value: "Shivamogga", text: "Shivamogga" },
  {
    key: "Shravanabelagola",
    value: "Shravanabelagola",
    text: "Shravanabelagola",
  },
  {
    key: "Shrirangapattana",
    value: "Shrirangapattana",
    text: "Shrirangapattana",
  },
  { key: "Tumkuru", value: "Tumkuru", text: "Tumkuru" },
  { key: "Kerala", value: "Kerala", text: "Kerala" },
  { key: "Alappuzha", value: "Alappuzha", text: "Alappuzha" },
  { key: "Badagara", value: "Badagara", text: "Badagara" },
  { key: "Idukki", value: "Idukki", text: "Idukki" },
  { key: "Kannur", value: "Kannur", text: "Kannur" },
  { key: "Kochi", value: "Kochi", text: "Kochi" },
  { key: "Kollam", value: "Kollam", text: "Kollam" },
  { key: "Kottayam", value: "Kottayam", text: "Kottayam" },
  { key: "Kozhikode", value: "Kozhikode", text: "Kozhikode" },
  { key: "Mattancheri", value: "Mattancheri", text: "Mattancheri" },
  { key: "Palakkad", value: "Palakkad", text: "Palakkad" },
  { key: "Thalassery", value: "Thalassery", text: "Thalassery" },
  {
    key: "Thiruvananthapuram",
    value: "Thiruvananthapuram",
    text: "Thiruvananthapuram",
  },
  { key: "Thrissur", value: "Thrissur", text: "Thrissur" },
  { key: "Madhya Pradesh", value: "Madhya Pradesh", text: "Madhya Pradesh" },
  { key: "Balaghat", value: "Balaghat", text: "Balaghat" },
  { key: "Barwani", value: "Barwani", text: "Barwani" },
  { key: "Betul", value: "Betul", text: "Betul" },
  { key: "Bharhut", value: "Bharhut", text: "Bharhut" },
  { key: "Bhind", value: "Bhind", text: "Bhind" },
  { key: "Bhojpur", value: "Bhojpur", text: "Bhojpur" },
  { key: "Bhopal", value: "Bhopal", text: "Bhopal" },
  { key: "Burhanpur", value: "Burhanpur", text: "Burhanpur" },
  { key: "Chhatarpur", value: "Chhatarpur", text: "Chhatarpur" },
  { key: "Chhindwara", value: "Chhindwara", text: "Chhindwara" },
  { key: "Damoh", value: "Damoh", text: "Damoh" },
  { key: "Datia", value: "Datia", text: "Datia" },
  { key: "Dewas", value: "Dewas", text: "Dewas" },
  { key: "Dhar", value: "Dhar", text: "Dhar" },
  { key: "Guna", value: "Guna", text: "Guna" },
  { key: "Gwalior", value: "Gwalior", text: "Gwalior" },
  { key: "Hoshangabad", value: "Hoshangabad", text: "Hoshangabad" },
  { key: "Indore", value: "Indore", text: "Indore" },
  { key: "Itarsi", value: "Itarsi", text: "Itarsi" },
  { key: "Jabalpur", value: "Jabalpur", text: "Jabalpur" },
  { key: "Jhabua", value: "Jhabua", text: "Jhabua" },
  { key: "Khajuraho", value: "Khajuraho", text: "Khajuraho" },
  { key: "Khandwa", value: "Khandwa", text: "Khandwa" },
  { key: "Khargon", value: "Khargon", text: "Khargon" },
  { key: "Maheshwar", value: "Maheshwar", text: "Maheshwar" },
  { key: "Mandla", value: "Mandla", text: "Mandla" },
  { key: "Mandsaur", value: "Mandsaur", text: "Mandsaur" },
  { key: "Mhow", value: "Mhow", text: "Mhow" },
  { key: "Morena", value: "Morena", text: "Morena" },
  { key: "Murwara", value: "Murwara", text: "Murwara" },
  { key: "Narsimhapur", value: "Narsimhapur", text: "Narsimhapur" },
  { key: "Narsinghgarh", value: "Narsinghgarh", text: "Narsinghgarh" },
  { key: "Narwar", value: "Narwar", text: "Narwar" },
  { key: "Neemuch", value: "Neemuch", text: "Neemuch" },
  { key: "Nowgong", value: "Nowgong", text: "Nowgong" },
  { key: "Orchha", value: "Orchha", text: "Orchha" },
  { key: "Panna", value: "Panna", text: "Panna" },
  { key: "Raisen", value: "Raisen", text: "Raisen" },
  { key: "Rajgarh", value: "Rajgarh", text: "Rajgarh" },
  { key: "Ratlam", value: "Ratlam", text: "Ratlam" },
  { key: "Rewa", value: "Rewa", text: "Rewa" },
  { key: "Sagar", value: "Sagar", text: "Sagar" },
  { key: "Sarangpur", value: "Sarangpur", text: "Sarangpur" },
  { key: "Satna", value: "Satna", text: "Satna" },
  { key: "Sehore", value: "Sehore", text: "Sehore" },
  { key: "Seoni", value: "Seoni", text: "Seoni" },
  { key: "Shahdol", value: "Shahdol", text: "Shahdol" },
  { key: "Shajapur", value: "Shajapur", text: "Shajapur" },
  { key: "Sheopur", value: "Sheopur", text: "Sheopur" },
  { key: "Shivpuri", value: "Shivpuri", text: "Shivpuri" },
  { key: "Ujjain", value: "Ujjain", text: "Ujjain" },
  { key: "Vidisha", value: "Vidisha", text: "Vidisha" },
  { key: "Maharashtra", value: "Maharashtra", text: "Maharashtra" },
  { key: "Ahmadnagar", value: "Ahmadnagar", text: "Ahmadnagar" },
  { key: "Akola", value: "Akola", text: "Akola" },
  { key: "Amravati", value: "Amravati", text: "Amravati" },
  { key: "Aurangabad", value: "Aurangabad", text: "Aurangabad" },
  { key: "Bhandara", value: "Bhandara", text: "Bhandara" },
  { key: "Bhusawal", value: "Bhusawal", text: "Bhusawal" },
  { key: "Bid", value: "Bid", text: "Bid" },
  { key: "Buldana", value: "Buldana", text: "Buldana" },
  { key: "Chandrapur", value: "Chandrapur", text: "Chandrapur" },
  { key: "Daulatabad", value: "Daulatabad", text: "Daulatabad" },
  { key: "Dhule", value: "Dhule", text: "Dhule" },
  { key: "Jalgaon", value: "Jalgaon", text: "Jalgaon" },
  { key: "Kalyan", value: "Kalyan", text: "Kalyan" },
  { key: "Karli", value: "Karli", text: "Karli" },
  { key: "Kolhapur", value: "Kolhapur", text: "Kolhapur" },
  { key: "Mahabaleshwar", value: "Mahabaleshwar", text: "Mahabaleshwar" },
  { key: "Malegaon", value: "Malegaon", text: "Malegaon" },
  { key: "Matheran", value: "Matheran", text: "Matheran" },
  { key: "Mumbai", value: "Mumbai", text: "Mumbai" },
  { key: "Nagpur", value: "Nagpur", text: "Nagpur" },
  { key: "Nanded", value: "Nanded", text: "Nanded" },
  { key: "Nashik", value: "Nashik", text: "Nashik" },
  { key: "Osmanabad", value: "Osmanabad", text: "Osmanabad" },
  { key: "Pandharpur", value: "Pandharpur", text: "Pandharpur" },
  { key: "Parbhani", value: "Parbhani", text: "Parbhani" },
  { key: "Pune", value: "Pune", text: "Pune" },
  { key: "Ratnagiri", value: "Ratnagiri", text: "Ratnagiri" },
  { key: "Sangli", value: "Sangli", text: "Sangli" },
  { key: "Satara", value: "Satara", text: "Satara" },
  { key: "Sevagram", value: "Sevagram", text: "Sevagram" },
  { key: "Solapur", value: "Solapur", text: "Solapur" },
  { key: "Thane", value: "Thane", text: "Thane" },
  { key: "Ulhasnagar", value: "Ulhasnagar", text: "Ulhasnagar" },
  { key: "Vasai Virar", value: "Vasai Virar", text: "Vasai Virar" },
  { key: "Wardha", value: "Wardha", text: "Wardha" },
  { key: "Yavatmal", value: "Yavatmal", text: "Yavatmal" },
  { key: "Manipur", value: "Manipur", text: "Manipur" },
  { key: "Imphal", value: "Imphal", text: "Imphal" },
  { key: "Meghalaya", value: "Meghalaya", text: "Meghalaya" },
  { key: "Cherrapunji", value: "Cherrapunji", text: "Cherrapunji" },
  { key: "Shillong", value: "Shillong", text: "Shillong" },
  { key: "Mizoram", value: "Mizoram", text: "Mizoram" },
  { key: "Aizawl", value: "Aizawl", text: "Aizawl" },
  { key: "Lunglei", value: "Lunglei", text: "Lunglei" },
  { key: "Nagaland", value: "Nagaland", text: "Nagaland" },
  { key: "Kohima", value: "Kohima", text: "Kohima" },
  { key: "Mon", value: "Mon", text: "Mon" },
  { key: "Phek", value: "Phek", text: "Phek" },
  { key: "Wokha", value: "Wokha", text: "Wokha" },
  { key: "Zunheboto", value: "Zunheboto", text: "Zunheboto" },
  { key: "Odisha", value: "Odisha", text: "Odisha" },
  { key: "Balangir", value: "Balangir", text: "Balangir" },
  { key: "Baleshwar", value: "Baleshwar", text: "Baleshwar" },
  { key: "Baripada", value: "Baripada", text: "Baripada" },
  { key: "Bhubaneshwar", value: "Bhubaneshwar", text: "Bhubaneshwar" },
  { key: "Brahmapur", value: "Brahmapur", text: "Brahmapur" },
  { key: "Cuttack", value: "Cuttack", text: "Cuttack" },
  { key: "Dhenkanal", value: "Dhenkanal", text: "Dhenkanal" },
  { key: "Keonjhar", value: "Keonjhar", text: "Keonjhar" },
  { key: "Konark", value: "Konark", text: "Konark" },
  { key: "Koraput", value: "Koraput", text: "Koraput" },
  { key: "Paradip", value: "Paradip", text: "Paradip" },
  { key: "Phulabani", value: "Phulabani", text: "Phulabani" },
  { key: "Puri", value: "Puri", text: "Puri" },
  { key: "Sambalpur", value: "Sambalpur", text: "Sambalpur" },
  { key: "Udayagiri", value: "Udayagiri", text: "Udayagiri" },
  { key: "Puducherry", value: "Puducherry", text: "Puducherry" },
  { key: "Karaikal", value: "Karaikal", text: "Karaikal" },
  { key: "Mahe", value: "Mahe", text: "Mahe" },
  { key: "Yanam", value: "Yanam", text: "Yanam" },
  { key: "Punjab", value: "Punjab", text: "Punjab" },
  { key: "Amritsar", value: "Amritsar", text: "Amritsar" },
  { key: "Batala", value: "Batala", text: "Batala" },
  { key: "Faridkot", value: "Faridkot", text: "Faridkot" },
  { key: "Firozpur", value: "Firozpur", text: "Firozpur" },
  { key: "Gurdaspur", value: "Gurdaspur", text: "Gurdaspur" },
  { key: "Hoshiarpur", value: "Hoshiarpur", text: "Hoshiarpur" },
  { key: "Jalandhar", value: "Jalandhar", text: "Jalandhar" },
  { key: "Kapurthala", value: "Kapurthala", text: "Kapurthala" },
  { key: "Ludhiana", value: "Ludhiana", text: "Ludhiana" },
  { key: "Nabha", value: "Nabha", text: "Nabha" },
  { key: "Patiala", value: "Patiala", text: "Patiala" },
  { key: "Rupnagar", value: "Rupnagar", text: "Rupnagar" },
  { key: "Sangrur", value: "Sangrur", text: "Sangrur" },
  { key: "Rajasthan", value: "Rajasthan", text: "Rajasthan" },
  { key: "Abu", value: "Abu", text: "Abu" },
  { key: "Ajmer", value: "Ajmer", text: "Ajmer" },
  { key: "Alwar", value: "Alwar", text: "Alwar" },
  { key: "Amer", value: "Amer", text: "Amer" },
  { key: "Barmer", value: "Barmer", text: "Barmer" },
  { key: "Beawar", value: "Beawar", text: "Beawar" },
  { key: "Bharatpur", value: "Bharatpur", text: "Bharatpur" },
  { key: "Bhilwara", value: "Bhilwara", text: "Bhilwara" },
  { key: "Bikaner", value: "Bikaner", text: "Bikaner" },
  { key: "Bundi", value: "Bundi", text: "Bundi" },
  { key: "Chittaurgarh", value: "Chittaurgarh", text: "Chittaurgarh" },
  { key: "Churu", value: "Churu", text: "Churu" },
  { key: "Dhaulpur", value: "Dhaulpur", text: "Dhaulpur" },
  { key: "Dungarpur", value: "Dungarpur", text: "Dungarpur" },
  { key: "Ganganagar", value: "Ganganagar", text: "Ganganagar" },
  { key: "Hanumangarh", value: "Hanumangarh", text: "Hanumangarh" },
  { key: "Jaipur", value: "Jaipur", text: "Jaipur" },
  { key: "Jaisalmer", value: "Jaisalmer", text: "Jaisalmer" },
  { key: "Jalor", value: "Jalor", text: "Jalor" },
  { key: "Jhalawar", value: "Jhalawar", text: "Jhalawar" },
  { key: "Jhunjhunu", value: "Jhunjhunu", text: "Jhunjhunu" },
  { key: "Jodhpur", value: "Jodhpur", text: "Jodhpur" },
  { key: "Kishangarh", value: "Kishangarh", text: "Kishangarh" },
  { key: "Kota", value: "Kota", text: "Kota" },
  { key: "Merta", value: "Merta", text: "Merta" },
  { key: "Nagaur", value: "Nagaur", text: "Nagaur" },
  { key: "Nathdwara", value: "Nathdwara", text: "Nathdwara" },
  { key: "Pali", value: "Pali", text: "Pali" },
  { key: "Phalodi", value: "Phalodi", text: "Phalodi" },
  { key: "Pushkar", value: "Pushkar", text: "Pushkar" },
  { key: "Sawai Madhopur", value: "Sawai Madhopur", text: "Sawai Madhopur" },
  { key: "Shahpura", value: "Shahpura", text: "Shahpura" },
  { key: "Sikar", value: "Sikar", text: "Sikar" },
  { key: "Sirohi", value: "Sirohi", text: "Sirohi" },
  { key: "Tonk", value: "Tonk", text: "Tonk" },
  { key: "Udaipur", value: "Udaipur", text: "Udaipur" },
  { key: "Sikkim", value: "Sikkim", text: "Sikkim" },
  { key: "Gangtok", value: "Gangtok", text: "Gangtok" },
  { key: "Gyalsing", value: "Gyalsing", text: "Gyalsing" },
  { key: "Lachung", value: "Lachung", text: "Lachung" },
  { key: "Mangan", value: "Mangan", text: "Mangan" },
  { key: "Tamil Nadu", value: "Tamil Nadu", text: "Tamil Nadu" },
  { key: "Arcot", value: "Arcot", text: "Arcot" },
  { key: "Chengalpattu", value: "Chengalpattu", text: "Chengalpattu" },
  { key: "Chennai", value: "Chennai", text: "Chennai" },
  { key: "Chidambaram", value: "Chidambaram", text: "Chidambaram" },
  { key: "Coimbatore", value: "Coimbatore", text: "Coimbatore" },
  { key: "Cuddalore", value: "Cuddalore", text: "Cuddalore" },
  { key: "Dharmapuri", value: "Dharmapuri", text: "Dharmapuri" },
  { key: "Dindigul", value: "Dindigul", text: "Dindigul" },
  { key: "Erode", value: "Erode", text: "Erode" },
  { key: "Kanchipuram", value: "Kanchipuram", text: "Kanchipuram" },
  { key: "Kanniyakumari", value: "Kanniyakumari", text: "Kanniyakumari" },
  { key: "Kodaikanal", value: "Kodaikanal", text: "Kodaikanal" },
  { key: "Kumbakonam", value: "Kumbakonam", text: "Kumbakonam" },
  { key: "Madurai", value: "Madurai", text: "Madurai" },
  { key: "Mamallapuram", value: "Mamallapuram", text: "Mamallapuram" },
  { key: "Nagappattinam", value: "Nagappattinam", text: "Nagappattinam" },
  { key: "Nagercoil", value: "Nagercoil", text: "Nagercoil" },
  { key: "Palayankottai", value: "Palayankottai", text: "Palayankottai" },
  { key: "Pudukkottai", value: "Pudukkottai", text: "Pudukkottai" },
  { key: "Rajapalaiyam", value: "Rajapalaiyam", text: "Rajapalaiyam" },
  { key: "Ramanathapuram", value: "Ramanathapuram", text: "Ramanathapuram" },
  { key: "Salem", value: "Salem", text: "Salem" },
  { key: "Thanjavur", value: "Thanjavur", text: "Thanjavur" },
  {
    key: "Tiruchchirappalli",
    value: "Tiruchchirappalli",
    text: "Tiruchchirappalli",
  },
  { key: "Tirunelveli", value: "Tirunelveli", text: "Tirunelveli" },
  { key: "Tiruppur", value: "Tiruppur", text: "Tiruppur" },
  { key: "Tuticorin", value: "Tuticorin", text: "Tuticorin" },
  { key: "Udhagamandalam", value: "Udhagamandalam", text: "Udhagamandalam" },
  { key: "Vellore", value: "Vellore", text: "Vellore" },
  { key: "Telangana", value: "Telangana", text: "Telangana" },
  { key: "Hyderabad", value: "Hyderabad", text: "Hyderabad" },
  { key: "Karimnagar", value: "Karimnagar", text: "Karimnagar" },
  { key: "Khammam", value: "Khammam", text: "Khammam" },
  { key: "Mahbubnagar", value: "Mahbubnagar", text: "Mahbubnagar" },
  { key: "Nizamabad", value: "Nizamabad", text: "Nizamabad" },
  { key: "Sangareddi", value: "Sangareddi", text: "Sangareddi" },
  { key: "Warangal", value: "Warangal", text: "Warangal" },
  { key: "Tripura", value: "Tripura", text: "Tripura" },
  { key: "Agartala", value: "Agartala", text: "Agartala" },
  { key: "Uttar Pradesh", value: "Uttar Pradesh", text: "Uttar Pradesh" },
  { key: "Agra", value: "Agra", text: "Agra" },
  { key: "Aligarh", value: "Aligarh", text: "Aligarh" },
  { key: "Amroha", value: "Amroha", text: "Amroha" },
  { key: "Ayodhya", value: "Ayodhya", text: "Ayodhya" },
  { key: "Azamgarh", value: "Azamgarh", text: "Azamgarh" },
  { key: "Bahraich", value: "Bahraich", text: "Bahraich" },
  { key: "Ballia", value: "Ballia", text: "Ballia" },
  { key: "Banda", value: "Banda", text: "Banda" },
  { key: "Bara Banki", value: "Bara Banki", text: "Bara Banki" },
  { key: "Bareilly", value: "Bareilly", text: "Bareilly" },
  { key: "Basti", value: "Basti", text: "Basti" },
  { key: "Bijnor", value: "Bijnor", text: "Bijnor" },
  { key: "Bithur", value: "Bithur", text: "Bithur" },
  { key: "Budaun", value: "Budaun", text: "Budaun" },
  { key: "Bulandshahr", value: "Bulandshahr", text: "Bulandshahr" },
  { key: "Deoria", value: "Deoria", text: "Deoria" },
  { key: "Etah", value: "Etah", text: "Etah" },
  { key: "Etawah", value: "Etawah", text: "Etawah" },
  { key: "Faizabad", value: "Faizabad", text: "Faizabad" },
  {
    key: "Farrukhabad cum Fatehgarh",
    value: "Farrukhabad cum Fatehgarh",
    text: "Farrukhabad cum Fatehgarh",
  },
  { key: "Fatehpur", value: "Fatehpur", text: "Fatehpur" },
  { key: "Fatehpur Sikri", value: "Fatehpur Sikri", text: "Fatehpur Sikri" },
  { key: "Ghaziabad", value: "Ghaziabad", text: "Ghaziabad" },
  { key: "Ghazipur", value: "Ghazipur", text: "Ghazipur" },
  { key: "Gonda", value: "Gonda", text: "Gonda" },
  { key: "Gorakhpur", value: "Gorakhpur", text: "Gorakhpur" },
  { key: "Hardoi", value: "Hardoi", text: "Hardoi" },
  { key: "Hathras", value: "Hathras", text: "Hathras" },
  { key: "Jalaun", value: "Jalaun", text: "Jalaun" },
  { key: "Jaunpur", value: "Jaunpur", text: "Jaunpur" },
  { key: "Jhansi", value: "Jhansi", text: "Jhansi" },
  { key: "Kannauj", value: "Kannauj", text: "Kannauj" },
  { key: "Kanpur", value: "Kanpur", text: "Kanpur" },
  { key: "Lakhimpur", value: "Lakhimpur", text: "Lakhimpur" },
  { key: "Lalitpur", value: "Lalitpur", text: "Lalitpur" },
  { key: "Lucknow", value: "Lucknow", text: "Lucknow" },
  { key: "Mainpuri", value: "Mainpuri", text: "Mainpuri" },
  { key: "Mathura", value: "Mathura", text: "Mathura" },
  { key: "Meerut", value: "Meerut", text: "Meerut" },
  {
    key: "Mirzapur Vindhyachal",
    value: "Mirzapur Vindhyachal",
    text: "Mirzapur Vindhyachal",
  },
  { key: "Moradabad", value: "Moradabad", text: "Moradabad" },
  { key: "Muzaffarnagar", value: "Muzaffarnagar", text: "Muzaffarnagar" },
  { key: "Partapgarh", value: "Partapgarh", text: "Partapgarh" },
  { key: "Pilibhit", value: "Pilibhit", text: "Pilibhit" },
  { key: "Prayagraj", value: "Prayagraj", text: "Prayagraj" },
  { key: "Rae Bareli", value: "Rae Bareli", text: "Rae Bareli" },
  { key: "Rampur", value: "Rampur", text: "Rampur" },
  { key: "Saharanpur", value: "Saharanpur", text: "Saharanpur" },
  { key: "Sambhal", value: "Sambhal", text: "Sambhal" },
  { key: "Shahjahanpur", value: "Shahjahanpur", text: "Shahjahanpur" },
  { key: "Sitapur", value: "Sitapur", text: "Sitapur" },
  { key: "Sultanpur", value: "Sultanpur", text: "Sultanpur" },
  { key: "Tehri", value: "Tehri", text: "Tehri" },
  { key: "Varanasi", value: "Varanasi", text: "Varanasi" },
  { key: "Uttarakhand", value: "Uttarakhand", text: "Uttarakhand" },
  { key: "Almora", value: "Almora", text: "Almora" },
  { key: "Dehra Dun", value: "Dehra Dun", text: "Dehra Dun" },
  { key: "Haridwar", value: "Haridwar", text: "Haridwar" },
  { key: "Mussoorie", value: "Mussoorie", text: "Mussoorie" },
  { key: "Nainital", value: "Nainital", text: "Nainital" },
  { key: "Pithoragarh", value: "Pithoragarh", text: "Pithoragarh" },
  { key: "West Bengal", value: "West Bengal", text: "West Bengal" },
  { key: "Alipore", value: "Alipore", text: "Alipore" },
  { key: "Alipur Duar", value: "Alipur Duar", text: "Alipur Duar" },
  { key: "Asansol", value: "Asansol", text: "Asansol" },
  { key: "Baharampur", value: "Baharampur", text: "Baharampur" },
  { key: "Bally", value: "Bally", text: "Bally" },
  { key: "Balurghat", value: "Balurghat", text: "Balurghat" },
  { key: "Bankura", value: "Bankura", text: "Bankura" },
  { key: "Baranagar", value: "Baranagar", text: "Baranagar" },
  { key: "Barasat", value: "Barasat", text: "Barasat" },
  { key: "Barrackpore", value: "Barrackpore", text: "Barrackpore" },
  { key: "Basirhat", value: "Basirhat", text: "Basirhat" },
  { key: "Bhatpara", value: "Bhatpara", text: "Bhatpara" },
  { key: "Bishnupur", value: "Bishnupur", text: "Bishnupur" },
  { key: "Budge Budge", value: "Budge Budge", text: "Budge Budge" },
  { key: "Burdwan", value: "Burdwan", text: "Burdwan" },
  { key: "Chandernagore", value: "Chandernagore", text: "Chandernagore" },
  { key: "Darjiling", value: "Darjiling", text: "Darjiling" },
  { key: "Diamond Harbour", value: "Diamond Harbour", text: "Diamond Harbour" },
  { key: "Dum Dum", value: "Dum Dum", text: "Dum Dum" },
  { key: "Durgapur", value: "Durgapur", text: "Durgapur" },
  { key: "Halisahar", value: "Halisahar", text: "Halisahar" },
  { key: "Haora", value: "Haora", text: "Haora" },
  { key: "Hugli", value: "Hugli", text: "Hugli" },
  { key: "Ingraj Bazar", value: "Ingraj Bazar", text: "Ingraj Bazar" },
  { key: "Jalpaiguri", value: "Jalpaiguri", text: "Jalpaiguri" },
  { key: "Kalimpong", value: "Kalimpong", text: "Kalimpong" },
  { key: "Kamarhati", value: "Kamarhati", text: "Kamarhati" },
  { key: "Kanchrapara", value: "Kanchrapara", text: "Kanchrapara" },
  { key: "Kharagpur", value: "Kharagpur", text: "Kharagpur" },
  { key: "Koch Bihar", value: "Koch Bihar", text: "Koch Bihar" },
  { key: "Kolkata", value: "Kolkata", text: "Kolkata" },
  { key: "Krishnanagar", value: "Krishnanagar", text: "Krishnanagar" },
  { key: "Malda", value: "Malda", text: "Malda" },
  { key: "Midnapore", value: "Midnapore", text: "Midnapore" },
  { key: "Murshidabad", value: "Murshidabad", text: "Murshidabad" },
  { key: "Navadwip", value: "Navadwip", text: "Navadwip" },
  { key: "Palashi", value: "Palashi", text: "Palashi" },
  { key: "Panihati", value: "Panihati", text: "Panihati" },
  { key: "Purulia", value: "Purulia", text: "Purulia" },
  { key: "Raiganj", value: "Raiganj", text: "Raiganj" },
  { key: "Santipur", value: "Santipur", text: "Santipur" },
  { key: "Shantiniketan", value: "Shantiniketan", text: "Shantiniketan" },
  { key: "Shrirampur", value: "Shrirampur", text: "Shrirampur" },
  { key: "Siliguri", value: "Siliguri", text: "Siliguri" },
  { key: "Siuri", value: "Siuri", text: "Siuri" },
  { key: "Tamluk", value: "Tamluk", text: "Tamluk" },
  { key: "Titagarh", value: "Titagarh", text: "Titagarh" },
  { key: "Achhnera", value: "Achhnera", text: "Achhnera" },
  { key: "Adalaj", value: "Adalaj", text: "Adalaj" },
  { key: "Adoor", value: "Adoor", text: "Adoor" },
  { key: "Adyar", value: "Adyar", text: "Adyar" },
  { key: "Adra", value: "Adra", text: "Adra" },
  { key: "Afzalpur", value: "Afzalpur", text: "Afzalpur" },
  { key: "Akot", value: "Akot", text: "Akot" },
  { key: "Alipurduar", value: "Alipurduar", text: "Alipurduar" },
  { key: "Alirajpur", value: "Alirajpur", text: "Alirajpur" },
  { key: "Aluva", value: "Aluva", text: "Aluva" },
  { key: "Amalapuram", value: "Amalapuram", text: "Amalapuram" },
  { key: "Amalner", value: "Amalner", text: "Amalner" },
  { key: "Amaravathi", value: "Amaravathi", text: "Amaravathi" },
  { key: "Ambejogai", value: "Ambejogai", text: "Ambejogai" },
  { key: "Anakapalle", value: "Anakapalle", text: "Anakapalle" },
  { key: "Angul", value: "Angul", text: "Angul" },
  { key: "Anjar", value: "Anjar", text: "Anjar" },
  { key: "Anjangaon", value: "Anjangaon", text: "Anjangaon" },
  { key: "Ankleshwar", value: "Ankleshwar", text: "Ankleshwar" },
  { key: "Arakkonam", value: "Arakkonam", text: "Arakkonam" },
  { key: "Araria", value: "Araria", text: "Araria" },
  { key: "Arambagh", value: "Arambagh", text: "Arambagh" },
  { key: "Arsikere", value: "Arsikere", text: "Arsikere" },
  { key: "Aruppukkottai", value: "Aruppukkottai", text: "Aruppukkottai" },
  { key: "Arvi", value: "Arvi", text: "Arvi" },
  { key: "Arwal", value: "Arwal", text: "Arwal" },
  { key: "Asarganj", value: "Asarganj", text: "Asarganj" },
  { key: "Ashok Nagar", value: "Ashok Nagar", text: "Ashok Nagar" },
  { key: "Athni", value: "Athni", text: "Athni" },
  { key: "Attili", value: "Attili", text: "Attili" },
  { key: "Attingal", value: "Attingal", text: "Attingal" },
  { key: "Badrinath", value: "Badrinath", text: "Badrinath" },
  { key: "Bagepalli", value: "Bagepalli", text: "Bagepalli" },
  { key: "Bageshwar", value: "Bageshwar", text: "Bageshwar" },
  { key: "Bajpur", value: "Bajpur", text: "Bajpur" },
  { key: "Banaganipalli", value: "Banaganipalli", text: "Banaganipalli" },
  { key: "Bapatla", value: "Bapatla", text: "Bapatla" },
  { key: "Barauli", value: "Barauli", text: "Barauli" },
  { key: "Barbil", value: "Barbil", text: "Barbil" },
  { key: "Bargarh", value: "Bargarh", text: "Bargarh" },
  { key: "Barbigha", value: "Barbigha", text: "Barbigha" },
  { key: "Barkot", value: "Barkot", text: "Barkot" },
  { key: "Barpeta", value: "Barpeta", text: "Barpeta" },
  { key: "Bellampalle", value: "Bellampalle", text: "Bellampalle" },
  { key: "Belonia", value: "Belonia", text: "Belonia" },
  { key: "Bhabua", value: "Bhabua", text: "Bhabua" },
  { key: "Bhadrachalam", value: "Bhadrachalam", text: "Bhadrachalam" },
  { key: "Bhainsa", value: "Bhainsa", text: "Bhainsa" },
  { key: "Bhaiseena", value: "Bhaiseena", text: "Bhaiseena" },
  { key: "Bhatapara", value: "Bhatapara", text: "Bhatapara" },
  { key: "Bhawanipatna", value: "Bhawanipatna", text: "Bhawanipatna" },
  { key: "Bheemunipatnam", value: "Bheemunipatnam", text: "Bheemunipatnam" },
  { key: "Bhimtal", value: "Bhimtal", text: "Bhimtal" },
  { key: "Bhongir", value: "Bhongir", text: "Bhongir" },
  { key: "Bhowali", value: "Bhowali", text: "Bhowali" },
  { key: "Bhusawar", value: "Bhusawar", text: "Bhusawar" },
  { key: "Bobbili", value: "Bobbili", text: "Bobbili" },
  { key: "Bodhan", value: "Bodhan", text: "Bodhan" },
  { key: "Bongaigaon City", value: "Bongaigaon City", text: "Bongaigaon City" },
  { key: "Byasanagar", value: "Byasanagar", text: "Byasanagar" },
  { key: "Bagha Kusmar", value: "Bagha Kusmar", text: "Bagha Kusmar" },
  { key: "Charkhi Dadri", value: "Charkhi Dadri", text: "Charkhi Dadri" },
  { key: "Chatra", value: "Chatra", text: "Chatra" },
  { key: "Chalakudy", value: "Chalakudy", text: "Chalakudy" },
  { key: "Challakere", value: "Challakere", text: "Challakere" },
  {
    key: "Chamoli Gopeshwar",
    value: "Chamoli Gopeshwar",
    text: "Chamoli Gopeshwar",
  },
  { key: "Champawat", value: "Champawat", text: "Champawat" },
  { key: "Changanassery", value: "Changanassery", text: "Changanassery" },
  { key: "Chengannur", value: "Chengannur", text: "Chengannur" },
  { key: "Cooch Behar", value: "Cooch Behar", text: "Cooch Behar" },
  { key: "Cherthala", value: "Cherthala", text: "Cherthala" },
  { key: "Chhapra", value: "Chhapra", text: "Chhapra" },
  { key: "Chikkaballapur", value: "Chikkaballapur", text: "Chikkaballapur" },
  { key: "Chintamani", value: "Chintamani", text: "Chintamani" },
  { key: "Chirala", value: "Chirala", text: "Chirala" },
  { key: "Chirkunda", value: "Chirkunda", text: "Chirkunda" },
  { key: "Chirmiri", value: "Chirmiri", text: "Chirmiri" },
  { key: "Chandpara", value: "Chandpara", text: "Chandpara" },
  {
    key: "Chittur Thathamangalam",
    value: "Chittur Thathamangalam",
    text: "Chittur Thathamangalam",
  },
  { key: "Dalli Rajhara", value: "Dalli Rajhara", text: "Dalli Rajhara" },
  { key: "Medininagar", value: "Medininagar", text: "Medininagar" },
  { key: "Degana", value: "Degana", text: "Degana" },
  { key: "Devprayag", value: "Devprayag", text: "Devprayag" },
  { key: "Dharchula", value: "Dharchula", text: "Dharchula" },
  { key: "Dharmanagar", value: "Dharmanagar", text: "Dharmanagar" },
  { key: "Dhone", value: "Dhone", text: "Dhone" },
  { key: "Dhoraji", value: "Dhoraji", text: "Dhoraji" },
  { key: "Dhubri", value: "Dhubri", text: "Dhubri" },
  { key: "Dhuri", value: "Dhuri", text: "Dhuri" },
  { key: "Didihat", value: "Didihat", text: "Didihat" },
  { key: "Dineshpur", value: "Dineshpur", text: "Dineshpur" },
  { key: "Diphu", value: "Diphu", text: "Diphu" },
  { key: "Dogadda", value: "Dogadda", text: "Dogadda" },
  { key: "Doiwala", value: "Doiwala", text: "Doiwala" },
  { key: "Dumraon", value: "Dumraon", text: "Dumraon" },
  { key: "Dwarahat", value: "Dwarahat", text: "Dwarahat" },
  { key: "Darwha", value: "Darwha", text: "Darwha" },
  { key: "Ellenabad", value: "Ellenabad", text: "Ellenabad" },
  { key: "Farooqnagar", value: "Farooqnagar", text: "Farooqnagar" },
  { key: "Fatehabad", value: "Fatehabad", text: "Fatehabad" },
  { key: "Fazilka", value: "Fazilka", text: "Fazilka" },
  { key: "Forbesganj", value: "Forbesganj", text: "Forbesganj" },
  { key: "Firozpur Cantt", value: "Firozpur Cantt", text: "Firozpur Cantt" },
  { key: "Gadarpur", value: "Gadarpur", text: "Gadarpur" },
  { key: "Gadwal", value: "Gadwal", text: "Gadwal" },
  { key: "Gangarampur", value: "Gangarampur", text: "Gangarampur" },
  { key: "Gangotri", value: "Gangotri", text: "Gangotri" },
  { key: "Gavaravaram", value: "Gavaravaram", text: "Gavaravaram" },
  { key: "Goalpara", value: "Goalpara", text: "Goalpara" },
  {
    key: "Gobichettipalayam",
    value: "Gobichettipalayam",
    text: "Gobichettipalayam",
  },
  { key: "Gobindgarh", value: "Gobindgarh", text: "Gobindgarh" },
  { key: "Gochar", value: "Gochar", text: "Gochar" },
  { key: "Gohana", value: "Gohana", text: "Gohana" },
  { key: "Golaghat", value: "Golaghat", text: "Golaghat" },
  { key: "Gokak", value: "Gokak", text: "Gokak" },
  { key: "Gooty", value: "Gooty", text: "Gooty" },
  { key: "Gopalganj", value: "Gopalganj", text: "Gopalganj" },
  { key: "Gowribidanur", value: "Gowribidanur", text: "Gowribidanur" },
  { key: "Gudur", value: "Gudur", text: "Gudur" },
  { key: "Gunupur", value: "Gunupur", text: "Gunupur" },
  { key: "Gumia", value: "Gumia", text: "Gumia" },
  { key: "Guruvayoor", value: "Guruvayoor", text: "Guruvayoor" },
  { key: "Herbertpur", value: "Herbertpur", text: "Herbertpur" },
  { key: "Inkollu", value: "Inkollu", text: "Inkollu" },
  { key: "Jaggaiahpet", value: "Jaggaiahpet", text: "Jaggaiahpet" },
  { key: "Jagraon", value: "Jagraon", text: "Jagraon" },
  { key: "Jagtial", value: "Jagtial", text: "Jagtial" },
  { key: "Jalandhar Cantt", value: "Jalandhar Cantt", text: "Jalandhar Cantt" },
  { key: "Jammalamadugu", value: "Jammalamadugu", text: "Jammalamadugu" },
  { key: "Jamui", value: "Jamui", text: "Jamui" },
  { key: "Jangaon", value: "Jangaon", text: "Jangaon" },
  { key: "Jaspur", value: "Jaspur", text: "Jaspur" },
  { key: "Jatani", value: "Jatani", text: "Jatani" },
  {
    key: "Jaynagar Majilpur",
    value: "Jaynagar Majilpur",
    text: "Jaynagar Majilpur",
  },
  { key: "Jhabrera", value: "Jhabrera", text: "Jhabrera" },
  { key: "Jhargram", value: "Jhargram", text: "Jhargram" },
  { key: "Jharsuguda", value: "Jharsuguda", text: "Jharsuguda" },
  { key: "Jhumri Tilaiya", value: "Jhumri Tilaiya", text: "Jhumri Tilaiya" },
  { key: "Joshimath", value: "Joshimath", text: "Joshimath" },
  { key: "Kadi", value: "Kadi", text: "Kadi" },
  { key: "Kadiri", value: "Kadiri", text: "Kadiri" },
  { key: "Kagaznagar", value: "Kagaznagar", text: "Kagaznagar" },
  { key: "Kailasahar", value: "Kailasahar", text: "Kailasahar" },
  { key: "Kaladhungi", value: "Kaladhungi", text: "Kaladhungi" },
  { key: "Kallakurichi", value: "Kallakurichi", text: "Kallakurichi" },
  { key: "Kalpi", value: "Kalpi", text: "Kalpi" },
  { key: "Kamareddy", value: "Kamareddy", text: "Kamareddy" },
  { key: "Kanigiri", value: "Kanigiri", text: "Kanigiri" },
  { key: "Kandukur", value: "Kandukur", text: "Kandukur" },
  { key: "Kanhangad", value: "Kanhangad", text: "Kanhangad" },
  { key: "Kapadvanj", value: "Kapadvanj", text: "Kapadvanj" },
  { key: "Karimganj", value: "Karimganj", text: "Karimganj" },
  { key: "Karjat", value: "Karjat", text: "Karjat" },
  { key: "Karnaprayag", value: "Karnaprayag", text: "Karnaprayag" },
  { key: "Karunagappally", value: "Karunagappally", text: "Karunagappally" },
  { key: "Karur", value: "Karur", text: "Karur" },
  { key: "Kasaragod", value: "Kasaragod", text: "Kasaragod" },
  { key: "Kavali", value: "Kavali", text: "Kavali" },
  { key: "Kayamkulam", value: "Kayamkulam", text: "Kayamkulam" },
  { key: "Kedarnath", value: "Kedarnath", text: "Kedarnath" },
  { key: "Kela Khera", value: "Kela Khera", text: "Kela Khera" },
  { key: "Kendrapara", value: "Kendrapara", text: "Kendrapara" },
  { key: "Kendujhar", value: "Kendujhar", text: "Kendujhar" },
  { key: "Keshod", value: "Keshod", text: "Keshod" },
  { key: "Khanda", value: "Khanda", text: "Khanda" },
  { key: "Kharar", value: "Kharar", text: "Kharar" },
  { key: "Khatima", value: "Khatima", text: "Khatima" },
  { key: "Khowai", value: "Khowai", text: "Khowai" },
  { key: "Kichha", value: "Kichha", text: "Kichha" },
  { key: "Kirtinagar", value: "Kirtinagar", text: "Kirtinagar" },
  { key: "Kodungallur", value: "Kodungallur", text: "Kodungallur" },
  { key: "Koratla", value: "Koratla", text: "Koratla" },
  { key: "Kot Kapura", value: "Kot Kapura", text: "Kot Kapura" },
  { key: "Kotdwar", value: "Kotdwar", text: "Kotdwar" },
  { key: "Kothagudem", value: "Kothagudem", text: "Kothagudem" },
  { key: "Kovvur", value: "Kovvur", text: "Kovvur" },
  { key: "Kunnamkulam", value: "Kunnamkulam", text: "Kunnamkulam" },
  { key: "Kyathampalle", value: "Kyathampalle", text: "Kyathampalle" },
  { key: "Kumarganj", value: "Kumarganj", text: "Kumarganj" },
  { key: "Lachhmangarh", value: "Lachhmangarh", text: "Lachhmangarh" },
  { key: "Ladnu", value: "Ladnu", text: "Ladnu" },
  { key: "Ladwa", value: "Ladwa", text: "Ladwa" },
  { key: "Lahar", value: "Lahar", text: "Lahar" },
  { key: "Laharpur", value: "Laharpur", text: "Laharpur" },
  { key: "Lakheri", value: "Lakheri", text: "Lakheri" },
  { key: "Lakhisarai", value: "Lakhisarai", text: "Lakhisarai" },
  { key: "Laksar", value: "Laksar", text: "Laksar" },
  { key: "Lakshmeshwar", value: "Lakshmeshwar", text: "Lakshmeshwar" },
  {
    key: "Lal Gopalganj Nindaura",
    value: "Lal Gopalganj Nindaura",
    text: "Lal Gopalganj Nindaura",
  },
  { key: "Lalganj", value: "Lalganj", text: "Lalganj" },
  { key: "Lalgudi", value: "Lalgudi", text: "Lalgudi" },
  { key: "Lalkuan", value: "Lalkuan", text: "Lalkuan" },
  { key: "Lalsot", value: "Lalsot", text: "Lalsot" },
  { key: "Landhaura", value: "Landhaura", text: "Landhaura" },
  { key: "Lanka", value: "Lanka", text: "Lanka" },
  { key: "Lar", value: "Lar", text: "Lar" },
  { key: "Lathi", value: "Lathi", text: "Lathi" },
  { key: "Lilong", value: "Lilong", text: "Lilong" },
  { key: "Limbdi", value: "Limbdi", text: "Limbdi" },
  { key: "Lingsugur", value: "Lingsugur", text: "Lingsugur" },
  { key: "Loha", value: "Loha", text: "Loha" },
  { key: "Lohaghat", value: "Lohaghat", text: "Lohaghat" },
  { key: "Lohardaga", value: "Lohardaga", text: "Lohardaga" },
  { key: "Lonar", value: "Lonar", text: "Lonar" },
  { key: "Lonavla", value: "Lonavla", text: "Lonavla" },
  { key: "Longowal", value: "Longowal", text: "Longowal" },
  { key: "Losal", value: "Losal", text: "Losal" },
  { key: "Lumding", value: "Lumding", text: "Lumding" },
  { key: "Lunawada", value: "Lunawada", text: "Lunawada" },
  { key: "Macherla", value: "Macherla", text: "Macherla" },
  { key: "Maddur", value: "Maddur", text: "Maddur" },
  { key: "Madhepura", value: "Madhepura", text: "Madhepura" },
  { key: "Madhugiri", value: "Madhugiri", text: "Madhugiri" },
  { key: "Madhupur", value: "Madhupur", text: "Madhupur" },
  { key: "Magadi", value: "Magadi", text: "Magadi" },
  { key: "Mahad", value: "Mahad", text: "Mahad" },
  { key: "Mahalingapura", value: "Mahalingapura", text: "Mahalingapura" },
  { key: "Maharajganj", value: "Maharajganj", text: "Maharajganj" },
  { key: "Maharajpur", value: "Maharajpur", text: "Maharajpur" },
  { key: "Mahasamund", value: "Mahasamund", text: "Mahasamund" },
  { key: "Manendragarh", value: "Manendragarh", text: "Manendragarh" },
  { key: "Mahendragarh", value: "Mahendragarh", text: "Mahendragarh" },
  { key: "Mahnar Bazar", value: "Mahnar Bazar", text: "Mahnar Bazar" },
  {
    key: "Mahua Dabra Haripura",
    value: "Mahua Dabra Haripura",
    text: "Mahua Dabra Haripura",
  },
  { key: "Mahua Kheraganj", value: "Mahua Kheraganj", text: "Mahua Kheraganj" },
  { key: "Maihar", value: "Maihar", text: "Maihar" },
  { key: "Mainaguri", value: "Mainaguri", text: "Mainaguri" },
  { key: "Makhdumpur", value: "Makhdumpur", text: "Makhdumpur" },
  { key: "Makrana", value: "Makrana", text: "Makrana" },
  { key: "Malaj Khand", value: "Malaj Khand", text: "Malaj Khand" },
  { key: "Malavalli", value: "Malavalli", text: "Malavalli" },
  { key: "Malkangiri", value: "Malkangiri", text: "Malkangiri" },
  { key: "Malkapur", value: "Malkapur", text: "Malkapur" },
  { key: "Malout", value: "Malout", text: "Malout" },
  { key: "Malpura", value: "Malpura", text: "Malpura" },
  { key: "Malur", value: "Malur", text: "Malur" },
  { key: "Manachanallur", value: "Manachanallur", text: "Manachanallur" },
  { key: "Manasa", value: "Manasa", text: "Manasa" },
  { key: "Manavadar", value: "Manavadar", text: "Manavadar" },
  { key: "Manawar", value: "Manawar", text: "Manawar" },
  { key: "Mandalgarh", value: "Mandalgarh", text: "Mandalgarh" },
  { key: "Mandamarri", value: "Mandamarri", text: "Mandamarri" },
  { key: "Mandapeta", value: "Mandapeta", text: "Mandapeta" },
  { key: "Mandawa", value: "Mandawa", text: "Mandawa" },
  { key: "Mandi Dabwali", value: "Mandi Dabwali", text: "Mandi Dabwali" },
  { key: "Mandideep", value: "Mandideep", text: "Mandideep" },
  { key: "Mandvi", value: "Mandvi", text: "Mandvi" },
  { key: "Maner Sharif", value: "Maner Sharif", text: "Maner Sharif" },
  { key: "Mangaldoi", value: "Mangaldoi", text: "Mangaldoi" },
  { key: "Mangalvedhe", value: "Mangalvedhe", text: "Mangalvedhe" },
  { key: "Manglaur", value: "Manglaur", text: "Manglaur" },
  { key: "Mangrol", value: "Mangrol", text: "Mangrol" },
  { key: "Mangrulpir", value: "Mangrulpir", text: "Mangrulpir" },
  { key: "Manihari", value: "Manihari", text: "Manihari" },
  { key: "Manjlegaon", value: "Manjlegaon", text: "Manjlegaon" },
  { key: "Mankachar", value: "Mankachar", text: "Mankachar" },
  { key: "Manmad", value: "Manmad", text: "Manmad" },
  { key: "Mansa", value: "Mansa", text: "Mansa" },
  { key: "Manuguru", value: "Manuguru", text: "Manuguru" },
  { key: "Manvi", value: "Manvi", text: "Manvi" },
  { key: "Manwath", value: "Manwath", text: "Manwath" },
  { key: "Mapusa", value: "Mapusa", text: "Mapusa" },
  { key: "Margao", value: "Margao", text: "Margao" },
  { key: "Margherita", value: "Margherita", text: "Margherita" },
  { key: "Marhaura", value: "Marhaura", text: "Marhaura" },
  { key: "Mariani", value: "Mariani", text: "Mariani" },
  { key: "Marigaon", value: "Marigaon", text: "Marigaon" },
  { key: "Markapur", value: "Markapur", text: "Markapur" },
  { key: "Masaurhi", value: "Masaurhi", text: "Masaurhi" },
  { key: "Mathabhanga", value: "Mathabhanga", text: "Mathabhanga" },
  { key: "Mattannur", value: "Mattannur", text: "Mattannur" },
  { key: "Mauganj", value: "Mauganj", text: "Mauganj" },
  { key: "Mavelikkara", value: "Mavelikkara", text: "Mavelikkara" },
  { key: "Mavoor", value: "Mavoor", text: "Mavoor" },
  { key: "Mayang Imphal", value: "Mayang Imphal", text: "Mayang Imphal" },
  { key: "Medak", value: "Medak", text: "Medak" },
  { key: "Medinipur", value: "Medinipur", text: "Medinipur" },
  { key: "Mehkar", value: "Mehkar", text: "Mehkar" },
  { key: "Mahemdabad", value: "Mahemdabad", text: "Mahemdabad" },
  { key: "Memari", value: "Memari", text: "Memari" },
  { key: "Merta City", value: "Merta City", text: "Merta City" },
  { key: "Mhaswad", value: "Mhaswad", text: "Mhaswad" },
  { key: "Mhow Cantonment", value: "Mhow Cantonment", text: "Mhow Cantonment" },
  { key: "Mhowgaon", value: "Mhowgaon", text: "Mhowgaon" },
  { key: "Mihijam", value: "Mihijam", text: "Mihijam" },
  { key: "Mirganj", value: "Mirganj", text: "Mirganj" },
  { key: "Miryalaguda", value: "Miryalaguda", text: "Miryalaguda" },
  { key: "Modasa", value: "Modasa", text: "Modasa" },
  { key: "Mokameh", value: "Mokameh", text: "Mokameh" },
  { key: "Mokokchung", value: "Mokokchung", text: "Mokokchung" },
  { key: "Monoharpur", value: "Monoharpur", text: "Monoharpur" },
  { key: "Morinda", value: "Morinda", text: "Morinda" },
  { key: "Morshi", value: "Morshi", text: "Morshi" },
  { key: "Motipur", value: "Motipur", text: "Motipur" },
  { key: "Mount Abu", value: "Mount Abu", text: "Mount Abu" },
  { key: "Mudalagi", value: "Mudalagi", text: "Mudalagi" },
  { key: "Mudabidri", value: "Mudabidri", text: "Mudabidri" },
  { key: "Muddebihal", value: "Muddebihal", text: "Muddebihal" },
  { key: "Mudhol", value: "Mudhol", text: "Mudhol" },
  { key: "Mukerian", value: "Mukerian", text: "Mukerian" },
  { key: "Mukhed", value: "Mukhed", text: "Mukhed" },
  { key: "Muktsar", value: "Muktsar", text: "Muktsar" },
  { key: "Mul", value: "Mul", text: "Mul" },
  { key: "Mulbagal", value: "Mulbagal", text: "Mulbagal" },
  { key: "Multai", value: "Multai", text: "Multai" },
  { key: "Mundi", value: "Mundi", text: "Mundi" },
  { key: "Mundargi", value: "Mundargi", text: "Mundargi" },
  { key: "Mungeli", value: "Mungeli", text: "Mungeli" },
  { key: "Muni Ki Reti", value: "Muni Ki Reti", text: "Muni Ki Reti" },
  { key: "Murliganj", value: "Murliganj", text: "Murliganj" },
  { key: "Murtijapur", value: "Murtijapur", text: "Murtijapur" },
  { key: "Musabani", value: "Musabani", text: "Musabani" },
  { key: "Muvattupuzha", value: "Muvattupuzha", text: "Muvattupuzha" },
  { key: "MUZAFFARPUR", value: "MUZAFFARPUR", text: "MUZAFFARPUR" },
  { key: "Nabarangapur", value: "Nabarangapur", text: "Nabarangapur" },
  { key: "Nadbai", value: "Nadbai", text: "Nadbai" },
  { key: "Nagar", value: "Nagar", text: "Nagar" },
  { key: "Nagari", value: "Nagari", text: "Nagari" },
  { key: "Nagarkurnool", value: "Nagarkurnool", text: "Nagarkurnool" },
  { key: "Nagina", value: "Nagina", text: "Nagina" },
  { key: "Nagla", value: "Nagla", text: "Nagla" },
  { key: "Naharlagun", value: "Naharlagun", text: "Naharlagun" },
  { key: "Naidupet", value: "Naidupet", text: "Naidupet" },
  { key: "Naila Janjgir", value: "Naila Janjgir", text: "Naila Janjgir" },
  { key: "Nainpur", value: "Nainpur", text: "Nainpur" },
  { key: "Najibabad", value: "Najibabad", text: "Najibabad" },
  { key: "Nakodar", value: "Nakodar", text: "Nakodar" },
  { key: "Nakur", value: "Nakur", text: "Nakur" },
  { key: "Nalbari", value: "Nalbari", text: "Nalbari" },
  { key: "Namagiripettai", value: "Namagiripettai", text: "Namagiripettai" },
  { key: "Namakkal", value: "Namakkal", text: "Namakkal" },
  { key: "Nandaprayag", value: "Nandaprayag", text: "Nandaprayag" },
  { key: "Nandgaon", value: "Nandgaon", text: "Nandgaon" },
  {
    key: "Nandivaram Guduvancheri",
    value: "Nandivaram Guduvancheri",
    text: "Nandivaram Guduvancheri",
  },
  { key: "Nandura", value: "Nandura", text: "Nandura" },
  { key: "Nangal", value: "Nangal", text: "Nangal" },
  { key: "Nanjangud", value: "Nanjangud", text: "Nanjangud" },
  { key: "Nanjikottai", value: "Nanjikottai", text: "Nanjikottai" },
  { key: "Nanpara", value: "Nanpara", text: "Nanpara" },
  { key: "Narasapuram", value: "Narasapuram", text: "Narasapuram" },
  { key: "Naraura", value: "Naraura", text: "Naraura" },
  { key: "Narayanpet", value: "Narayanpet", text: "Narayanpet" },
  { key: "Narendranagar", value: "Narendranagar", text: "Narendranagar" },
  { key: "Nargund", value: "Nargund", text: "Nargund" },
  { key: "Narkatiaganj", value: "Narkatiaganj", text: "Narkatiaganj" },
  { key: "Narkhed", value: "Narkhed", text: "Narkhed" },
  { key: "Narnaul", value: "Narnaul", text: "Narnaul" },
  { key: "Narsipatnam", value: "Narsipatnam", text: "Narsipatnam" },
  { key: "Narwana", value: "Narwana", text: "Narwana" },
  { key: "Nasirabad", value: "Nasirabad", text: "Nasirabad" },
  { key: "Natham", value: "Natham", text: "Natham" },
  { key: "Naugachhia", value: "Naugachhia", text: "Naugachhia" },
  { key: "Naugawan Sadat", value: "Naugawan Sadat", text: "Naugawan Sadat" },
  { key: "Naura", value: "Naura", text: "Naura" },
  { key: "Nautanwa", value: "Nautanwa", text: "Nautanwa" },
  { key: "Navalgund", value: "Navalgund", text: "Navalgund" },
  { key: "Nawabganj", value: "Nawabganj", text: "Nawabganj" },
  { key: "Nawada", value: "Nawada", text: "Nawada" },
  { key: "Nawanshahr", value: "Nawanshahr", text: "Nawanshahr" },
  { key: "Nawapur", value: "Nawapur", text: "Nawapur" },
  { key: "Nedumangad", value: "Nedumangad", text: "Nedumangad" },
  { key: "Nedumbassery", value: "Nedumbassery", text: "Nedumbassery" },
  { key: "Neem Ka Thana", value: "Neem Ka Thana", text: "Neem Ka Thana" },
  { key: "Nehtaur", value: "Nehtaur", text: "Nehtaur" },
  { key: "Nelamangala", value: "Nelamangala", text: "Nelamangala" },
  { key: "Nellikuppam", value: "Nellikuppam", text: "Nellikuppam" },
  { key: "Nepanagar", value: "Nepanagar", text: "Nepanagar" },
  { key: "Neyyattinkara", value: "Neyyattinkara", text: "Neyyattinkara" },
  { key: "Nidadavole", value: "Nidadavole", text: "Nidadavole" },
  { key: "Nilanga", value: "Nilanga", text: "Nilanga" },
  { key: "Nilambur", value: "Nilambur", text: "Nilambur" },
  { key: "Nimbahera", value: "Nimbahera", text: "Nimbahera" },
  { key: "Nirmal", value: "Nirmal", text: "Nirmal" },
  { key: "Niwari", value: "Niwari", text: "Niwari" },
  { key: "Niwai", value: "Niwai", text: "Niwai" },
  { key: "Nohar", value: "Nohar", text: "Nohar" },
  { key: "Nokha", value: "Nokha", text: "Nokha" },
  { key: "Nongstoin", value: "Nongstoin", text: "Nongstoin" },
  { key: "Noorpur", value: "Noorpur", text: "Noorpur" },
  { key: "North Lakhimpur", value: "North Lakhimpur", text: "North Lakhimpur" },
  { key: "Nowrozabad", value: "Nowrozabad", text: "Nowrozabad" },
  { key: "Nuzvid", value: "Nuzvid", text: "Nuzvid" },
  { key: "O Valley", value: "O Valley", text: "O Valley" },
  { key: "Oddanchatram", value: "Oddanchatram", text: "Oddanchatram" },
  { key: "Obra", value: "Obra", text: "Obra" },
  { key: "Ottappalam", value: "Ottappalam", text: "Ottappalam" },
  { key: "Ozar", value: "Ozar", text: "Ozar" },
  { key: "Owk", value: "Owk", text: "Owk" },
  { key: "P N Patti", value: "P N Patti", text: "P N Patti" },
  { key: "Palampur", value: "Palampur", text: "Palampur" },
  { key: "Pachora", value: "Pachora", text: "Pachora" },
  { key: "Pachore", value: "Pachore", text: "Pachore" },
  { key: "Pacode", value: "Pacode", text: "Pacode" },
  { key: "Padmanabhapuram", value: "Padmanabhapuram", text: "Padmanabhapuram" },
  { key: "Padra", value: "Padra", text: "Padra" },
  { key: "Padrauna", value: "Padrauna", text: "Padrauna" },
  { key: "Paithan", value: "Paithan", text: "Paithan" },
  { key: "Pakaur", value: "Pakaur", text: "Pakaur" },
  { key: "Palai", value: "Palai", text: "Palai" },
  { key: "Palani", value: "Palani", text: "Palani" },
  {
    key: "Palasa Kasibugga",
    value: "Palasa Kasibugga",
    text: "Palasa Kasibugga",
  },
  { key: "Palghar", value: "Palghar", text: "Palghar" },
  { key: "Palia Kalan", value: "Palia Kalan", text: "Palia Kalan" },
  { key: "Palitana", value: "Palitana", text: "Palitana" },
  { key: "Palladam", value: "Palladam", text: "Palladam" },
  { key: "Pallapatti", value: "Pallapatti", text: "Pallapatti" },
  { key: "Pallikonda", value: "Pallikonda", text: "Pallikonda" },
  { key: "Palwancha", value: "Palwancha", text: "Palwancha" },
  { key: "Panagar", value: "Panagar", text: "Panagar" },
  { key: "Panagudi", value: "Panagudi", text: "Panagudi" },
  { key: "Panamattom", value: "Panamattom", text: "Panamattom" },
  { key: "Panchla", value: "Panchla", text: "Panchla" },
  { key: "Pandharkaoda", value: "Pandharkaoda", text: "Pandharkaoda" },
  { key: "Pandhurna", value: "Pandhurna", text: "Pandhurna" },
  { key: "Pandua", value: "Pandua", text: "Pandua" },
  { key: "Panniyannur", value: "Panniyannur", text: "Panniyannur" },
  { key: "Panruti", value: "Panruti", text: "Panruti" },
  { key: "Pappinisseri", value: "Pappinisseri", text: "Pappinisseri" },
  { key: "Paramakudi", value: "Paramakudi", text: "Paramakudi" },
  { key: "Parangipettai", value: "Parangipettai", text: "Parangipettai" },
  { key: "Parasi", value: "Parasi", text: "Parasi" },
  { key: "Paravoor", value: "Paravoor", text: "Paravoor" },
  { key: "Pardi", value: "Pardi", text: "Pardi" },
  { key: "Parlakhemundi", value: "Parlakhemundi", text: "Parlakhemundi" },
  { key: "Parli", value: "Parli", text: "Parli" },
  { key: "Partur", value: "Partur", text: "Partur" },
  { key: "Parvathipuram", value: "Parvathipuram", text: "Parvathipuram" },
  { key: "Pasan", value: "Pasan", text: "Pasan" },
  {
    key: "Paschim Punropara",
    value: "Paschim Punropara",
    text: "Paschim Punropara",
  },
  { key: "Pasighat", value: "Pasighat", text: "Pasighat" },
  { key: "Pathanamthitta", value: "Pathanamthitta", text: "Pathanamthitta" },
  { key: "Pathardi", value: "Pathardi", text: "Pathardi" },
  { key: "Pathri", value: "Pathri", text: "Pathri" },
  { key: "Pattran", value: "Pattran", text: "Pattran" },
  { key: "Patratu", value: "Patratu", text: "Patratu" },
  { key: "Pattamundai", value: "Pattamundai", text: "Pattamundai" },
  { key: "Patti", value: "Patti", text: "Patti" },
  { key: "Pattukkottai", value: "Pattukkottai", text: "Pattukkottai" },
  { key: "Patur", value: "Patur", text: "Patur" },
  { key: "Pauni", value: "Pauni", text: "Pauni" },
  { key: "Pauri", value: "Pauri", text: "Pauri" },
  { key: "Pavagada", value: "Pavagada", text: "Pavagada" },
  { key: "Pedana", value: "Pedana", text: "Pedana" },
  { key: "Peddapuram", value: "Peddapuram", text: "Peddapuram" },
  { key: "Pen", value: "Pen", text: "Pen" },
  { key: "Perambalur", value: "Perambalur", text: "Perambalur" },
  { key: "Peravurani", value: "Peravurani", text: "Peravurani" },
  { key: "Peringathur", value: "Peringathur", text: "Peringathur" },
  { key: "Perinthalmanna", value: "Perinthalmanna", text: "Perinthalmanna" },
  { key: "Periyakulam", value: "Periyakulam", text: "Periyakulam" },
  { key: "Periyasemur", value: "Periyasemur", text: "Periyasemur" },
  { key: "Pernampattu", value: "Pernampattu", text: "Pernampattu" },
  { key: "Perumbavoor", value: "Perumbavoor", text: "Perumbavoor" },
  { key: "Petlad", value: "Petlad", text: "Petlad" },
  { key: "Phaltan", value: "Phaltan", text: "Phaltan" },
  { key: "Phagwara", value: "Phagwara", text: "Phagwara" },
  { key: "Phillaur", value: "Phillaur", text: "Phillaur" },
  { key: "Phulera", value: "Phulera", text: "Phulera" },
  { key: "Phulpur", value: "Phulpur", text: "Phulpur" },
  { key: "Pihani", value: "Pihani", text: "Pihani" },
  { key: "Piler", value: "Piler", text: "Piler" },
  { key: "Pilani", value: "Pilani", text: "Pilani" },
  { key: "Pilibanga", value: "Pilibanga", text: "Pilibanga" },
  { key: "Pilkhuwa", value: "Pilkhuwa", text: "Pilkhuwa" },
  { key: "Pindwara", value: "Pindwara", text: "Pindwara" },
  { key: "Pipar City", value: "Pipar City", text: "Pipar City" },
  { key: "Piro", value: "Piro", text: "Piro" },
  { key: "Piriyapatna", value: "Piriyapatna", text: "Piriyapatna" },
  { key: "Pithampur", value: "Pithampur", text: "Pithampur" },
  { key: "Pithapuram", value: "Pithapuram", text: "Pithapuram" },
  { key: "Polur", value: "Polur", text: "Polur" },
  { key: "Ponnani", value: "Ponnani", text: "Ponnani" },
  { key: "Ponneri", value: "Ponneri", text: "Ponneri" },
  { key: "Ponnur", value: "Ponnur", text: "Ponnur" },
  { key: "Porsa", value: "Porsa", text: "Porsa" },
  { key: "Powayan", value: "Powayan", text: "Powayan" },
  { key: "Prantij", value: "Prantij", text: "Prantij" },
  { key: "Pratapgarh", value: "Pratapgarh", text: "Pratapgarh" },
  { key: "Prithvipur", value: "Prithvipur", text: "Prithvipur" },
  { key: "Pudupattinam", value: "Pudupattinam", text: "Pudupattinam" },
  { key: "Pukhrayan", value: "Pukhrayan", text: "Pukhrayan" },
  { key: "Pulgaon", value: "Pulgaon", text: "Pulgaon" },
  { key: "Puliyankudi", value: "Puliyankudi", text: "Puliyankudi" },
  { key: "Punalur", value: "Punalur", text: "Punalur" },
  { key: "Poonch", value: "Poonch", text: "Poonch" },
  { key: "Punjaipugalur", value: "Punjaipugalur", text: "Punjaipugalur" },
  { key: "Punganur", value: "Punganur", text: "Punganur" },
  { key: "Puranpur", value: "Puranpur", text: "Puranpur" },
  { key: "Purna", value: "Purna", text: "Purna" },
  { key: "Purquazi", value: "Purquazi", text: "Purquazi" },
  { key: "Purwa", value: "Purwa", text: "Purwa" },
  { key: "Pusad", value: "Pusad", text: "Pusad" },
  { key: "Puttur", value: "Puttur", text: "Puttur" },
  { key: "Puthuppally", value: "Puthuppally", text: "Puthuppally" },
  { key: "Qadian", value: "Qadian", text: "Qadian" },
  { key: "Koyilandy", value: "Koyilandy", text: "Koyilandy" },
  {
    key: "Rabkavi Banhatti",
    value: "Rabkavi Banhatti",
    text: "Rabkavi Banhatti",
  },
  { key: "Radhanpur", value: "Radhanpur", text: "Radhanpur" },
  { key: "Rafiganj", value: "Rafiganj", text: "Rafiganj" },
  {
    key: "Raghogarh Vijaypur",
    value: "Raghogarh Vijaypur",
    text: "Raghogarh Vijaypur",
  },
  { key: "Raghunathpur", value: "Raghunathpur", text: "Raghunathpur" },
  { key: "Rahatgarh", value: "Rahatgarh", text: "Rahatgarh" },
  { key: "Rahuri", value: "Rahuri", text: "Rahuri" },
  { key: "Raikot", value: "Raikot", text: "Raikot" },
  { key: "Rairangpur", value: "Rairangpur", text: "Rairangpur" },
  { key: "Raisinghnagar", value: "Raisinghnagar", text: "Raisinghnagar" },
  { key: "Rajagangapur", value: "Rajagangapur", text: "Rajagangapur" },
  { key: "Rajakhera", value: "Rajakhera", text: "Rajakhera" },
  { key: "Rajaldesar", value: "Rajaldesar", text: "Rajaldesar" },
  { key: "Rajam", value: "Rajam", text: "Rajam" },
  { key: "Rajesultanpur", value: "Rajesultanpur", text: "Rajesultanpur" },
  { key: "Rajgir", value: "Rajgir", text: "Rajgir" },
  { key: "Rajpipla", value: "Rajpipla", text: "Rajpipla" },
  { key: "Rajpura", value: "Rajpura", text: "Rajpura" },
  { key: "Rajsamand", value: "Rajsamand", text: "Rajsamand" },
  { key: "Rajula", value: "Rajula", text: "Rajula" },
  { key: "Rajura", value: "Rajura", text: "Rajura" },
  {
    key: "Ramachandrapuram",
    value: "Ramachandrapuram",
    text: "Ramachandrapuram",
  },
  { key: "Ramnagar", value: "Ramnagar", text: "Ramnagar" },
  { key: "Ramanagaram", value: "Ramanagaram", text: "Ramanagaram" },
  { key: "Ramdurg", value: "Ramdurg", text: "Ramdurg" },
  { key: "Rameshwaram", value: "Rameshwaram", text: "Rameshwaram" },
  { key: "Ramganj Mandi", value: "Ramganj Mandi", text: "Ramganj Mandi" },
  { key: "Ramngarh", value: "Ramngarh", text: "Ramngarh" },
  {
    key: "Rampur Maniharan",
    value: "Rampur Maniharan",
    text: "Rampur Maniharan",
  },
  { key: "Rampura Phul", value: "Rampura Phul", text: "Rampura Phul" },
  { key: "Rampurhat", value: "Rampurhat", text: "Rampurhat" },
  { key: "Ramtek", value: "Ramtek", text: "Ramtek" },
  { key: "Ranavav", value: "Ranavav", text: "Ranavav" },
  { key: "Rangiya", value: "Rangiya", text: "Rangiya" },
  { key: "Rania", value: "Rania", text: "Rania" },
  { key: "Ranibennur", value: "Ranibennur", text: "Ranibennur" },
  { key: "Rapar", value: "Rapar", text: "Rapar" },
  { key: "Rasipuram", value: "Rasipuram", text: "Rasipuram" },
  { key: "Rasra", value: "Rasra", text: "Rasra" },
  { key: "Ratangarh", value: "Ratangarh", text: "Ratangarh" },
  { key: "Rath", value: "Rath", text: "Rath" },
  { key: "Ratia", value: "Ratia", text: "Ratia" },
  { key: "Rau", value: "Rau", text: "Rau" },
  { key: "Raver", value: "Raver", text: "Raver" },
  { key: "Rawatbhata", value: "Rawatbhata", text: "Rawatbhata" },
  { key: "Rawatsar", value: "Rawatsar", text: "Rawatsar" },
  { key: "Raxaul Bazar", value: "Raxaul Bazar", text: "Raxaul Bazar" },
  { key: "Rayachoti", value: "Rayachoti", text: "Rayachoti" },
  { key: "Rayadurg", value: "Rayadurg", text: "Rayadurg" },
  { key: "Rayagada", value: "Rayagada", text: "Rayagada" },
  { key: "Reengus", value: "Reengus", text: "Reengus" },
  { key: "Rehli", value: "Rehli", text: "Rehli" },
  { key: "Renigunta", value: "Renigunta", text: "Renigunta" },
  { key: "Renukoot", value: "Renukoot", text: "Renukoot" },
  { key: "Reoti", value: "Reoti", text: "Reoti" },
  { key: "Repalle", value: "Repalle", text: "Repalle" },
  { key: "Revelganj", value: "Revelganj", text: "Revelganj" },
  { key: "Rishikesh", value: "Rishikesh", text: "Rishikesh" },
  { key: "Risod", value: "Risod", text: "Risod" },
  { key: "Robertsganj", value: "Robertsganj", text: "Robertsganj" },
  { key: "Ron", value: "Ron", text: "Ron" },
  { key: "Rosera", value: "Rosera", text: "Rosera" },
  { key: "Rudauli", value: "Rudauli", text: "Rudauli" },
  { key: "Rudraprayag", value: "Rudraprayag", text: "Rudraprayag" },
  { key: "Rudrapur", value: "Rudrapur", text: "Rudrapur" },
  { key: "Sabalgarh", value: "Sabalgarh", text: "Sabalgarh" },
  { key: "Sadabad", value: "Sadabad", text: "Sadabad" },
  { key: "Sadasivpet", value: "Sadasivpet", text: "Sadasivpet" },
  { key: "Sadri", value: "Sadri", text: "Sadri" },
  { key: "Sadulshahar", value: "Sadulshahar", text: "Sadulshahar" },
  { key: "Safidon", value: "Safidon", text: "Safidon" },
  { key: "Safipur", value: "Safipur", text: "Safipur" },
  { key: "Sagara", value: "Sagara", text: "Sagara" },
  { key: "Sagwara", value: "Sagwara", text: "Sagwara" },
  { key: "Sahaspur", value: "Sahaspur", text: "Sahaspur" },
  { key: "Sahaswan", value: "Sahaswan", text: "Sahaswan" },
  { key: "Sahawar", value: "Sahawar", text: "Sahawar" },
  { key: "Sahibganj", value: "Sahibganj", text: "Sahibganj" },
  { key: "Sahjanwa", value: "Sahjanwa", text: "Sahjanwa" },
  { key: "Saidpur", value: "Saidpur", text: "Saidpur" },
  { key: "Saiha", value: "Saiha", text: "Saiha" },
  { key: "Sailu", value: "Sailu", text: "Sailu" },
  { key: "Sainthia", value: "Sainthia", text: "Sainthia" },
  { key: "Sakaleshapura", value: "Sakaleshapura", text: "Sakaleshapura" },
  { key: "Sakti", value: "Sakti", text: "Sakti" },
  { key: "Salaya", value: "Salaya", text: "Salaya" },
  { key: "Salur", value: "Salur", text: "Salur" },
  { key: "Samalkha", value: "Samalkha", text: "Samalkha" },
  { key: "Samalkot", value: "Samalkot", text: "Samalkot" },
  { key: "Samana", value: "Samana", text: "Samana" },
  { key: "Sambhar", value: "Sambhar", text: "Sambhar" },
  { key: "Samdhan", value: "Samdhan", text: "Samdhan" },
  { key: "Samthar", value: "Samthar", text: "Samthar" },
  { key: "Sanand", value: "Sanand", text: "Sanand" },
  { key: "Sanawad", value: "Sanawad", text: "Sanawad" },
  { key: "Sanchore", value: "Sanchore", text: "Sanchore" },
  { key: "Sanivarapupeta", value: "Sanivarapupeta", text: "Sanivarapupeta" },
  { key: "Sarsod", value: "Sarsod", text: "Sarsod" },
  { key: "Sindagi", value: "Sindagi", text: "Sindagi" },
  { key: "Sandi", value: "Sandi", text: "Sandi" },
  { key: "Sandila", value: "Sandila", text: "Sandila" },
  { key: "Sanduru", value: "Sanduru", text: "Sanduru" },
  { key: "Sangamner", value: "Sangamner", text: "Sangamner" },
  { key: "Sangareddy", value: "Sangareddy", text: "Sangareddy" },
  { key: "Sangaria", value: "Sangaria", text: "Sangaria" },
  { key: "Sangole", value: "Sangole", text: "Sangole" },
  { key: "Sankarankovil", value: "Sankarankovil", text: "Sankarankovil" },
  { key: "Sankari", value: "Sankari", text: "Sankari" },
  { key: "Sankeshwara", value: "Sankeshwara", text: "Sankeshwara" },
  { key: "Sardarshahar", value: "Sardarshahar", text: "Sardarshahar" },
  { key: "Sardhana", value: "Sardhana", text: "Sardhana" },
  { key: "Sarni", value: "Sarni", text: "Sarni" },
  { key: "Sarsawa", value: "Sarsawa", text: "Sarsawa" },
  { key: "Sasvad", value: "Sasvad", text: "Sasvad" },
  { key: "Satana", value: "Satana", text: "Satana" },
  { key: "Sathyamangalam", value: "Sathyamangalam", text: "Sathyamangalam" },
  { key: "Satrampadu", value: "Satrampadu", text: "Satrampadu" },
  { key: "Sattenapalle", value: "Sattenapalle", text: "Sattenapalle" },
  { key: "Sattur", value: "Sattur", text: "Sattur" },
  { key: "Saunda", value: "Saunda", text: "Saunda" },
  {
    key: "Saundatti Yellamma",
    value: "Saundatti Yellamma",
    text: "Saundatti Yellamma",
  },
  { key: "Sausar", value: "Sausar", text: "Sausar" },
  { key: "Savarkundla", value: "Savarkundla", text: "Savarkundla" },
  { key: "Savanur", value: "Savanur", text: "Savanur" },
  { key: "Savner", value: "Savner", text: "Savner" },
  { key: "Sawantwadi", value: "Sawantwadi", text: "Sawantwadi" },
  { key: "Sedam", value: "Sedam", text: "Sedam" },
  { key: "Sendhwa", value: "Sendhwa", text: "Sendhwa" },
  { key: "Seohara", value: "Seohara", text: "Seohara" },
  { key: "Seoni Malwa", value: "Seoni Malwa", text: "Seoni Malwa" },
  { key: "Shahabad", value: "Shahabad", text: "Shahabad" },
  { key: "Shahade", value: "Shahade", text: "Shahade" },
  { key: "Shahbad", value: "Shahbad", text: "Shahbad" },
  { key: "Shahganj", value: "Shahganj", text: "Shahganj" },
  { key: "Shahpur", value: "Shahpur", text: "Shahpur" },
  { key: "Shaktigarh", value: "Shaktigarh", text: "Shaktigarh" },
  { key: "Shamgarh", value: "Shamgarh", text: "Shamgarh" },
  { key: "Shamli", value: "Shamli", text: "Shamli" },
  { key: "Shamsabad", value: "Shamsabad", text: "Shamsabad" },
  { key: "Shegaon", value: "Shegaon", text: "Shegaon" },
  { key: "Sheikhpura", value: "Sheikhpura", text: "Sheikhpura" },
  { key: "Shendurjana", value: "Shendurjana", text: "Shendurjana" },
  { key: "Shenkottai", value: "Shenkottai", text: "Shenkottai" },
  { key: "Sheoganj", value: "Sheoganj", text: "Sheoganj" },
  { key: "Sheohar", value: "Sheohar", text: "Sheohar" },
  { key: "Sherghati", value: "Sherghati", text: "Sherghati" },
  { key: "Sherkot", value: "Sherkot", text: "Sherkot" },
  { key: "Shiggaon", value: "Shiggaon", text: "Shiggaon" },
  { key: "Shikaripur", value: "Shikaripur", text: "Shikaripur" },
  { key: "Shikarpur", value: "Shikarpur", text: "Shikarpur" },
  { key: "Shikohabad", value: "Shikohabad", text: "Shikohabad" },
  { key: "Shirdi", value: "Shirdi", text: "Shirdi" },
  { key: "Shirpur Warwade", value: "Shirpur Warwade", text: "Shirpur Warwade" },
  { key: "Shirur", value: "Shirur", text: "Shirur" },
  { key: "Shishgarh", value: "Shishgarh", text: "Shishgarh" },
  { key: "Sholavandan", value: "Sholavandan", text: "Sholavandan" },
  { key: "Sholingur", value: "Sholingur", text: "Sholingur" },
  { key: "Shoranur", value: "Shoranur", text: "Shoranur" },
  { key: "Surapura", value: "Surapura", text: "Surapura" },
  { key: "Shrigonda", value: "Shrigonda", text: "Shrigonda" },
  { key: "Shujalpur", value: "Shujalpur", text: "Shujalpur" },
  { key: "Siana", value: "Siana", text: "Siana" },
  { key: "Siddipet", value: "Siddipet", text: "Siddipet" },
  { key: "Sidhi", value: "Sidhi", text: "Sidhi" },
  { key: "Sidhpur", value: "Sidhpur", text: "Sidhpur" },
  { key: "Sidlaghatta", value: "Sidlaghatta", text: "Sidlaghatta" },
  { key: "Sihor", value: "Sihor", text: "Sihor" },
  { key: "Sihora", value: "Sihora", text: "Sihora" },
  { key: "Sikanderpur", value: "Sikanderpur", text: "Sikanderpur" },
  { key: "Sikandra Rao", value: "Sikandra Rao", text: "Sikandra Rao" },
  { key: "Sikandrabad", value: "Sikandrabad", text: "Sikandrabad" },
  { key: "Silao", value: "Silao", text: "Silao" },
  { key: "Silapathar", value: "Silapathar", text: "Silapathar" },
  { key: "Sillod", value: "Sillod", text: "Sillod" },
  { key: "Simdega", value: "Simdega", text: "Simdega" },
  { key: "Sindhagi", value: "Sindhagi", text: "Sindhagi" },
  { key: "Sindhnur", value: "Sindhnur", text: "Sindhnur" },
  { key: "Sinnar", value: "Sinnar", text: "Sinnar" },
  { key: "Sira", value: "Sira", text: "Sira" },
  { key: "Sircilla", value: "Sircilla", text: "Sircilla" },
  {
    key: "Sirhind Fatehgarh Sahib",
    value: "Sirhind Fatehgarh Sahib",
    text: "Sirhind Fatehgarh Sahib",
  },
  { key: "Sirkali", value: "Sirkali", text: "Sirkali" },
  { key: "Sironj", value: "Sironj", text: "Sironj" },
  { key: "Sirsaganj", value: "Sirsaganj", text: "Sirsaganj" },
  { key: "Sirsi", value: "Sirsi", text: "Sirsi" },

  { key: "Siruguppa", value: "Siruguppa", text: "Siruguppa" },
  { key: "Sitarganj", value: "Sitarganj", text: "Sitarganj" },
  { key: "Sivaganga", value: "Sivaganga", text: "Sivaganga" },
  { key: "Sivagiri", value: "Sivagiri", text: "Sivagiri" },
  { key: "Sohagpur", value: "Sohagpur", text: "Sohagpur" },
  { key: "Sohna", value: "Sohna", text: "Sohna" },
  { key: "Sojat", value: "Sojat", text: "Sojat" },
  { key: "Solan", value: "Solan", text: "Solan" },
  { key: "Sonamukhi", value: "Sonamukhi", text: "Sonamukhi" },
  { key: "Sonepur", value: "Sonepur", text: "Sonepur" },
  { key: "Songadh", value: "Songadh", text: "Songadh" },
  { key: "Sopore", value: "Sopore", text: "Sopore" },
  { key: "Soro", value: "Soro", text: "Soro" },
  { key: "Soron", value: "Soron", text: "Soron" },
  { key: "Soyagaon", value: "Soyagaon", text: "Soyagaon" },
  { key: "Sri Madhopur", value: "Sri Madhopur", text: "Sri Madhopur" },
  { key: "Srikalahasti", value: "Srikalahasti", text: "Srikalahasti" },
  { key: "Srinivaspur", value: "Srinivaspur", text: "Srinivaspur" },
  { key: "Srisailam", value: "Srisailam", text: "Srisailam" },
  { key: "Srirampore", value: "Srirampore", text: "Srirampore" },
  { key: "Srivilliputhur", value: "Srivilliputhur", text: "Srivilliputhur" },
  { key: "Suar", value: "Suar", text: "Suar" },
  { key: "Sugauli", value: "Sugauli", text: "Sugauli" },
  { key: "Sujangarh", value: "Sujangarh", text: "Sujangarh" },
  { key: "Sujanpur", value: "Sujanpur", text: "Sujanpur" },
  { key: "Sultanganj", value: "Sultanganj", text: "Sultanganj" },
  { key: "Sullurpeta", value: "Sullurpeta", text: "Sullurpeta" },
  { key: "Sumerpur", value: "Sumerpur", text: "Sumerpur" },

  { key: "Sunabeda", value: "Sunabeda", text: "Sunabeda" },
  { key: "Sunam", value: "Sunam", text: "Sunam" },
  { key: "Sundargarh", value: "Sundargarh", text: "Sundargarh" },
  { key: "Sundarnagar", value: "Sundarnagar", text: "Sundarnagar" },
  { key: "Supaul", value: "Supaul", text: "Supaul" },
  { key: "Surandai", value: "Surandai", text: "Surandai" },
  { key: "Suratgarh", value: "Suratgarh", text: "Suratgarh" },
  { key: "Suri", value: "Suri", text: "Suri" },
  { key: "Suriyampalayam", value: "Suriyampalayam", text: "Suriyampalayam" },
  { key: "Takhatgarh", value: "Takhatgarh", text: "Takhatgarh" },
  { key: "Taki", value: "Taki", text: "Taki" },
  { key: "Talaja", value: "Talaja", text: "Talaja" },
  { key: "Talcher", value: "Talcher", text: "Talcher" },
  {
    key: "Talegaon Dabhade",
    value: "Talegaon Dabhade",
    text: "Talegaon Dabhade",
  },
  { key: "Taliparamba", value: "Taliparamba", text: "Taliparamba" },
  { key: "Talode", value: "Talode", text: "Talode" },
  { key: "Talwara", value: "Talwara", text: "Talwara" },
  { key: "Tanakpur", value: "Tanakpur", text: "Tanakpur" },
  { key: "Tanda", value: "Tanda", text: "Tanda" },
  { key: "Tandur", value: "Tandur", text: "Tandur" },
  { key: "Tanuku", value: "Tanuku", text: "Tanuku" },
  { key: "Tarakeswar", value: "Tarakeswar", text: "Tarakeswar" },
  { key: "Tarana", value: "Tarana", text: "Tarana" },
  { key: "Taranagar", value: "Taranagar", text: "Taranagar" },
  { key: "Taraori", value: "Taraori", text: "Taraori" },
  { key: "Tarbha", value: "Tarbha", text: "Tarbha" },
  { key: "Tarikere", value: "Tarikere", text: "Tarikere" },
  { key: "Tarn Taran", value: "Tarn Taran", text: "Tarn Taran" },
  { key: "Tasgaon", value: "Tasgaon", text: "Tasgaon" },
  { key: "Tekkalakote", value: "Tekkalakote", text: "Tekkalakote" },
  { key: "Tenkasi", value: "Tenkasi", text: "Tenkasi" },
  {
    key: "Tenu dam cum Kathhara",
    value: "Tenu dam cum Kathhara",
    text: "Tenu dam cum Kathhara",
  },
  { key: "Terdal", value: "Terdal", text: "Terdal" },
  { key: "Thakurdwara", value: "Thakurdwara", text: "Thakurdwara" },
  { key: "Thammampatti", value: "Thammampatti", text: "Thammampatti" },
  { key: "Thana Bhawan", value: "Thana Bhawan", text: "Thana Bhawan" },
  { key: "Thangadh", value: "Thangadh", text: "Thangadh" },
  { key: "Tharad", value: "Tharad", text: "Tharad" },
  { key: "Tharamangalam", value: "Tharamangalam", text: "Tharamangalam" },
  { key: "Tharangambadi", value: "Tharangambadi", text: "Tharangambadi" },
  {
    key: "Theni Allinagaram",
    value: "Theni Allinagaram",
    text: "Theni Allinagaram",
  },
  { key: "Thirumangalam", value: "Thirumangalam", text: "Thirumangalam" },
  { key: "Thirupuvanam", value: "Thirupuvanam", text: "Thirupuvanam" },
  {
    key: "Thiruthuraipoondi",
    value: "Thiruthuraipoondi",
    text: "Thiruthuraipoondi",
  },
  { key: "Thiruvalla", value: "Thiruvalla", text: "Thiruvalla" },
  { key: "Thiruvallur", value: "Thiruvallur", text: "Thiruvallur" },
  { key: "Thiruvarur", value: "Thiruvarur", text: "Thiruvarur" },
  { key: "Thodupuzha", value: "Thodupuzha", text: "Thodupuzha" },
  { key: "Thoubal", value: "Thoubal", text: "Thoubal" },
  { key: "Thrippunithura", value: "Thrippunithura", text: "Thrippunithura" },
  { key: "Thuraiyur", value: "Thuraiyur", text: "Thuraiyur" },
  { key: "Tikamgarh", value: "Tikamgarh", text: "Tikamgarh" },
  { key: "Tilda Newra", value: "Tilda Newra", text: "Tilda Newra" },
  { key: "Tilhar", value: "Tilhar", text: "Tilhar" },
  { key: "Talikota", value: "Talikota", text: "Talikota" },
  { key: "Tindivanam", value: "Tindivanam", text: "Tindivanam" },
  { key: "Tiptur", value: "Tiptur", text: "Tiptur" },
  { key: "Tirora", value: "Tirora", text: "Tirora" },
  { key: "Tiruchendur", value: "Tiruchendur", text: "Tiruchendur" },
  { key: "Tiruchengode", value: "Tiruchengode", text: "Tiruchengode" },
  { key: "Tirukalukundram", value: "Tirukalukundram", text: "Tirukalukundram" },
  { key: "Tirukkoyilur", value: "Tirukkoyilur", text: "Tirukkoyilur" },
  { key: "Tirupathur", value: "Tirupathur", text: "Tirupathur" },
  { key: "Tirur", value: "Tirur", text: "Tirur" },
  { key: "Tiruttani", value: "Tiruttani", text: "Tiruttani" },
  { key: "Tiruvethipuram", value: "Tiruvethipuram", text: "Tiruvethipuram" },
  { key: "Tiruvuru", value: "Tiruvuru", text: "Tiruvuru" },
  { key: "Tirwaganj", value: "Tirwaganj", text: "Tirwaganj" },
  { key: "Titlagarh", value: "Titlagarh", text: "Titlagarh" },
  { key: "Tittakudi", value: "Tittakudi", text: "Tittakudi" },
  { key: "Todabhim", value: "Todabhim", text: "Todabhim" },
  { key: "Todaraisingh", value: "Todaraisingh", text: "Todaraisingh" },
  { key: "Tohana", value: "Tohana", text: "Tohana" },
  { key: "Tuensang", value: "Tuensang", text: "Tuensang" },
  { key: "Tuljapur", value: "Tuljapur", text: "Tuljapur" },
  { key: "Tulsipur", value: "Tulsipur", text: "Tulsipur" },
  { key: "Tumsar", value: "Tumsar", text: "Tumsar" },
  { key: "Tundla", value: "Tundla", text: "Tundla" },
  { key: "Tuni", value: "Tuni", text: "Tuni" },
  { key: "Tura", value: "Tura", text: "Tura" },
  { key: "Uchgaon", value: "Uchgaon", text: "Uchgaon" },
  { key: "Udaipurwati", value: "Udaipurwati", text: "Udaipurwati" },
  { key: "Udumalaipettai", value: "Udumalaipettai", text: "Udumalaipettai" },
  { key: "Ujhani", value: "Ujhani", text: "Ujhani" },
  { key: "Umarga", value: "Umarga", text: "Umarga" },
  { key: "Umaria", value: "Umaria", text: "Umaria" },
  { key: "Umarkhed", value: "Umarkhed", text: "Umarkhed" },
  { key: "Umbergaon", value: "Umbergaon", text: "Umbergaon" },
  { key: "Umred", value: "Umred", text: "Umred" },
  { key: "Umreth", value: "Umreth", text: "Umreth" },
  { key: "Unjha", value: "Unjha", text: "Unjha" },
  { key: "Unnamalaikadai", value: "Unnamalaikadai", text: "Unnamalaikadai" },
  { key: "Upleta", value: "Upleta", text: "Upleta" },
  { key: "Uran", value: "Uran", text: "Uran" },
  { key: "Uran Islampur", value: "Uran Islampur", text: "Uran Islampur" },
  { key: "Uravakonda", value: "Uravakonda", text: "Uravakonda" },
  { key: "Urmar Tanda", value: "Urmar Tanda", text: "Urmar Tanda" },
  { key: "Usilampatti", value: "Usilampatti", text: "Usilampatti" },
  { key: "Uthamapalayam", value: "Uthamapalayam", text: "Uthamapalayam" },
  { key: "Uthiramerur", value: "Uthiramerur", text: "Uthiramerur" },
  { key: "Utraula", value: "Utraula", text: "Utraula" },
  { key: "Uttarkashi", value: "Uttarkashi", text: "Uttarkashi" },
  { key: "Vadakkuvalliyur", value: "Vadakkuvalliyur", text: "Vadakkuvalliyur" },
  { key: "Vadalur", value: "Vadalur", text: "Vadalur" },
  { key: "Vadgaon Kasba", value: "Vadgaon Kasba", text: "Vadgaon Kasba" },
  { key: "vasudevanallur", value: "vasudevanallur", text: "vasudevanallur" },
  { key: "Vadnagar", value: "Vadnagar", text: "Vadnagar" },
  { key: "Vaijapur", value: "Vaijapur", text: "Vaijapur" },
  { key: "Vaikom", value: "Vaikom", text: "Vaikom" },
  { key: "Valparai", value: "Valparai", text: "Valparai" },
  { key: "Vandavasi", value: "Vandavasi", text: "Vandavasi" },
  { key: "Vaniyambadi", value: "Vaniyambadi", text: "Vaniyambadi" },
  { key: "Vapi", value: "Vapi", text: "Vapi" },
  { key: "Varandarappilly", value: "Varandarappilly", text: "Varandarappilly" },
  { key: "Varkala", value: "Varkala", text: "Varkala" },
  { key: "Vatakara", value: "Vatakara", text: "Vatakara" },
  { key: "Vedaranyam", value: "Vedaranyam", text: "Vedaranyam" },
  { key: "Vellakoil", value: "Vellakoil", text: "Vellakoil" },
  { key: "Venkatagiri", value: "Venkatagiri", text: "Venkatagiri" },
  { key: "Vijainagar", value: "Vijainagar", text: "Vijainagar" },
  { key: "Vijapur", value: "Vijapur", text: "Vijapur" },
  { key: "Vijaypur", value: "Vijaypur", text: "Vijaypur" },
  { key: "Vijayapura", value: "Vijayapura", text: "Vijayapura" },
  { key: "Vikarabad", value: "Vikarabad", text: "Vikarabad" },
  { key: "Vikasnagar", value: "Vikasnagar", text: "Vikasnagar" },
  {
    key: "Vikramasingapuram",
    value: "Vikramasingapuram",
    text: "Vikramasingapuram",
  },
  { key: "Viluppuram", value: "Viluppuram", text: "Viluppuram" },
  { key: "Vinukonda", value: "Vinukonda", text: "Vinukonda" },
  { key: "Viramgam", value: "Viramgam", text: "Viramgam" },
  { key: "Virudhachalam", value: "Virudhachalam", text: "Virudhachalam" },
  { key: "Virudhunagar", value: "Virudhunagar", text: "Virudhunagar" },
  { key: "Visnagar", value: "Visnagar", text: "Visnagar" },
  { key: "Viswanatham", value: "Viswanatham", text: "Viswanatham" },
  { key: "Vita", value: "Vita", text: "Vita" },
  { key: "Vrindavan", value: "Vrindavan", text: "Vrindavan" },
  { key: "Vyara", value: "Vyara", text: "Vyara" },
  { key: "Wadgaon Road", value: "Wadgaon Road", text: "Wadgaon Road" },
  { key: "Wadhwan", value: "Wadhwan", text: "Wadhwan" },
  { key: "Wadi", value: "Wadi", text: "Wadi" },
  { key: "Wai", value: "Wai", text: "Wai" },
  { key: "Wanaparthy", value: "Wanaparthy", text: "Wanaparthy" },
  { key: "Wani", value: "Wani", text: "Wani" },
  { key: "Wankaner", value: "Wankaner", text: "Wankaner" },
  { key: "Wara Seoni", value: "Wara Seoni", text: "Wara Seoni" },
  { key: "Warhapur", value: "Warhapur", text: "Warhapur" },
  { key: "Warisaliganj", value: "Warisaliganj", text: "Warisaliganj" },
  { key: "Warora", value: "Warora", text: "Warora" },
  { key: "Warud", value: "Warud", text: "Warud" },
  { key: "Washim", value: "Washim", text: "Washim" },
  { key: "Yadgir", value: "Yadgir", text: "Yadgir" },
  { key: "Yawal", value: "Yawal", text: "Yawal" },
  { key: "Yellandu", value: "Yellandu", text: "Yellandu" },
  { key: "Yerraguntla", value: "Yerraguntla", text: "Yerraguntla" },
  { key: "Yevla", value: "Yevla", text: "Yevla" },
  { key: "Zaidpur", value: "Zaidpur", text: "Zaidpur" },
  { key: "Zamania", value: "Zamania", text: "Zamania" },
  { key: "Zira", value: "Zira", text: "Zira" },
  { key: "Zirakpur", value: "Zirakpur", text: "Zirakpur" },
  { key: "Bombay", value: "Bombay", text: "Bombay" },
  { key: "Madras", value: "Madras", text: "Madras" },
  { key: "Roorkee", value: "Roorkee", text: "Roorkee" },
  { key: "Calcutta", value: "Calcutta", text: "Calcutta" },

  { key: "Gurugram", value: "Gurugram", text: "Gurugram" },
  { key: "Rourkela", value: "Rourkela", text: "Rourkela" },
  { key: "Mohali", value: "Mohali", text: "Mohali" },
  { key: "Ahmedabad", value: "Ahmedabad", text: "Ahmedabad" },
  { key: "Kashipur", value: "Kashipur", text: "Kashipur" },
  { key: "Tiruchirappalli", value: "Tiruchirappalli", text: "Tiruchirappalli" },
  { key: "Bhubaneswar", value: "Bhubaneswar", text: "Bhubaneswar" },
  { key: "Ropar", value: "Ropar", text: "Ropar" },
];

export const city = cities.sort(sortCityBasedOnKey);
